package com.ut.scf.pojo.auto;

import java.math.BigDecimal;
import java.util.Date;

public class OrderInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_id
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_id_yi
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private String orderIdYi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.product_id
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.goods_name
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.product_amt
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private BigDecimal productAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.finance_period
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private Byte financePeriod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.total_price
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.contract
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private String contract;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.cr_req_amt
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private BigDecimal crReqAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.start_pay_amt
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private BigDecimal startPayAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.pay_m
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private BigDecimal payM;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.paytime
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private Date paytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.state
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.batch_id
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private String batchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.stu_id
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private String stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.umm_truename
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private String ummTruename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.paid_period
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private Integer paidPeriod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.tongdun_res
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private String tongdunRes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.needmoney
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private BigDecimal needmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.service_money
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private Long serviceMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.ensure_money
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private BigDecimal ensureMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.loan_money
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private BigDecimal loanMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.store_id
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private String storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.people_type
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private Integer peopleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.td_score
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private String tdScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.quota
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private String quota;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.level
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    private String level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_id
     *
     * @return the value of order_info.order_id
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_id
     *
     * @param orderId the value for order_info.order_id
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_id_yi
     *
     * @return the value of order_info.order_id_yi
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public String getOrderIdYi() {
        return orderIdYi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_id_yi
     *
     * @param orderIdYi the value for order_info.order_id_yi
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setOrderIdYi(String orderIdYi) {
        this.orderIdYi = orderIdYi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.product_id
     *
     * @return the value of order_info.product_id
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.product_id
     *
     * @param productId the value for order_info.product_id
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.goods_name
     *
     * @return the value of order_info.goods_name
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.goods_name
     *
     * @param goodsName the value for order_info.goods_name
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.product_amt
     *
     * @return the value of order_info.product_amt
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public BigDecimal getProductAmt() {
        return productAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.product_amt
     *
     * @param productAmt the value for order_info.product_amt
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setProductAmt(BigDecimal productAmt) {
        this.productAmt = productAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.finance_period
     *
     * @return the value of order_info.finance_period
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public Byte getFinancePeriod() {
        return financePeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.finance_period
     *
     * @param financePeriod the value for order_info.finance_period
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setFinancePeriod(Byte financePeriod) {
        this.financePeriod = financePeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.total_price
     *
     * @return the value of order_info.total_price
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.total_price
     *
     * @param totalPrice the value for order_info.total_price
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.contract
     *
     * @return the value of order_info.contract
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public String getContract() {
        return contract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.contract
     *
     * @param contract the value for order_info.contract
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setContract(String contract) {
        this.contract = contract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.cr_req_amt
     *
     * @return the value of order_info.cr_req_amt
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public BigDecimal getCrReqAmt() {
        return crReqAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.cr_req_amt
     *
     * @param crReqAmt the value for order_info.cr_req_amt
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setCrReqAmt(BigDecimal crReqAmt) {
        this.crReqAmt = crReqAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.start_pay_amt
     *
     * @return the value of order_info.start_pay_amt
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public BigDecimal getStartPayAmt() {
        return startPayAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.start_pay_amt
     *
     * @param startPayAmt the value for order_info.start_pay_amt
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setStartPayAmt(BigDecimal startPayAmt) {
        this.startPayAmt = startPayAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.pay_m
     *
     * @return the value of order_info.pay_m
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public BigDecimal getPayM() {
        return payM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.pay_m
     *
     * @param payM the value for order_info.pay_m
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setPayM(BigDecimal payM) {
        this.payM = payM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.paytime
     *
     * @return the value of order_info.paytime
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.paytime
     *
     * @param paytime the value for order_info.paytime
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.state
     *
     * @return the value of order_info.state
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.state
     *
     * @param state the value for order_info.state
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.batch_id
     *
     * @return the value of order_info.batch_id
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.batch_id
     *
     * @param batchId the value for order_info.batch_id
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setBatchId(String batchId) {
        this.batchId = batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.stu_id
     *
     * @return the value of order_info.stu_id
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.stu_id
     *
     * @param stuId the value for order_info.stu_id
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setStuId(String stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.umm_truename
     *
     * @return the value of order_info.umm_truename
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public String getUmmTruename() {
        return ummTruename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.umm_truename
     *
     * @param ummTruename the value for order_info.umm_truename
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setUmmTruename(String ummTruename) {
        this.ummTruename = ummTruename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.paid_period
     *
     * @return the value of order_info.paid_period
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public Integer getPaidPeriod() {
        return paidPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.paid_period
     *
     * @param paidPeriod the value for order_info.paid_period
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setPaidPeriod(Integer paidPeriod) {
        this.paidPeriod = paidPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.tongdun_res
     *
     * @return the value of order_info.tongdun_res
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public String getTongdunRes() {
        return tongdunRes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.tongdun_res
     *
     * @param tongdunRes the value for order_info.tongdun_res
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setTongdunRes(String tongdunRes) {
        this.tongdunRes = tongdunRes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.needmoney
     *
     * @return the value of order_info.needmoney
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public BigDecimal getNeedmoney() {
        return needmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.needmoney
     *
     * @param needmoney the value for order_info.needmoney
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setNeedmoney(BigDecimal needmoney) {
        this.needmoney = needmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.service_money
     *
     * @return the value of order_info.service_money
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public Long getServiceMoney() {
        return serviceMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.service_money
     *
     * @param serviceMoney the value for order_info.service_money
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setServiceMoney(Long serviceMoney) {
        this.serviceMoney = serviceMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.ensure_money
     *
     * @return the value of order_info.ensure_money
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public BigDecimal getEnsureMoney() {
        return ensureMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.ensure_money
     *
     * @param ensureMoney the value for order_info.ensure_money
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setEnsureMoney(BigDecimal ensureMoney) {
        this.ensureMoney = ensureMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.loan_money
     *
     * @return the value of order_info.loan_money
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public BigDecimal getLoanMoney() {
        return loanMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.loan_money
     *
     * @param loanMoney the value for order_info.loan_money
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setLoanMoney(BigDecimal loanMoney) {
        this.loanMoney = loanMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.store_id
     *
     * @return the value of order_info.store_id
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.store_id
     *
     * @param storeId the value for order_info.store_id
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.people_type
     *
     * @return the value of order_info.people_type
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public Integer getPeopleType() {
        return peopleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.people_type
     *
     * @param peopleType the value for order_info.people_type
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setPeopleType(Integer peopleType) {
        this.peopleType = peopleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.td_score
     *
     * @return the value of order_info.td_score
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public String getTdScore() {
        return tdScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.td_score
     *
     * @param tdScore the value for order_info.td_score
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setTdScore(String tdScore) {
        this.tdScore = tdScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.quota
     *
     * @return the value of order_info.quota
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public String getQuota() {
        return quota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.quota
     *
     * @param quota the value for order_info.quota
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setQuota(String quota) {
        this.quota = quota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.level
     *
     * @return the value of order_info.level
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.level
     *
     * @param level the value for order_info.level
     *
     * @mbg.generated Thu Sep 06 15:54:23 GMT+08:00 2018
     */
    public void setLevel(String level) {
        this.level = level;
    }
}
