package com.ut.scf.pojo.auto;

public class ProductInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_info.product_id
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	private String productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_info.product_type
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	private Integer productType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_info.product_name
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	private String productName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_info.product_desc
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	private String productDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_info.attachment
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	private String attachment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_info.file_name
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	private String fileName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_info.file_name
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	private Integer businessType;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_info.product_id
	 * @return  the value of product_info.product_id
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	public String getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_info.product_id
	 * @param productId  the value for product_info.product_id
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	public void setProductId(String productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_info.product_type
	 * @return  the value of product_info.product_type
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	public Integer getProductType() {
		return productType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_info.product_type
	 * @param productType  the value for product_info.product_type
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	public void setProductType(Integer productType) {
		this.productType = productType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_info.product_name
	 * @return  the value of product_info.product_name
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_info.product_name
	 * @param productName  the value for product_info.product_name
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	public void setProductName(String productName) {
		this.productName = productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_info.product_desc
	 * @return  the value of product_info.product_desc
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	public String getProductDesc() {
		return productDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_info.product_desc
	 * @param productDesc  the value for product_info.product_desc
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	public void setProductDesc(String productDesc) {
		this.productDesc = productDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_info.attachment
	 * @return  the value of product_info.attachment
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	public String getAttachment() {
		return attachment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_info.attachment
	 * @param attachment  the value for product_info.attachment
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	public void setAttachment(String attachment) {
		this.attachment = attachment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_info.file_name
	 * @return  the value of product_info.file_name
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	public String getFileName() {
		return fileName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_info.file_name
	 * @param fileName  the value for product_info.file_name
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public Integer getBusinessType() {
		return businessType;
	}

	public void setBusinessType(Integer businessType) {
		this.businessType = businessType;
	}
}