package com.ut.scf.pojo.auto;

import java.math.BigDecimal;
import java.util.Date;

public class TfLoanInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tf_loan_info.id
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tf_loan_info.contract_no
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	private String contractNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tf_loan_info.loan_no
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	private String loanNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tf_loan_info.loan_amount
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	private BigDecimal loanAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tf_loan_info.loan_date
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	private Date loanDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tf_loan_info.loan_term
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	private Integer loanTerm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tf_loan_info.rate_id
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	private String rateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tf_loan_info.create_time
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tf_loan_info.deposit_rate
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	private BigDecimal depositRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tf_loan_info.repay_status
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	private String repayStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tf_loan_info.interest_amount
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	private BigDecimal interestAmount;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tf_loan_info.id
	 * @return  the value of tf_loan_info.id
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tf_loan_info.id
	 * @param id  the value for tf_loan_info.id
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tf_loan_info.contract_no
	 * @return  the value of tf_loan_info.contract_no
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	public String getContractNo() {
		return contractNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tf_loan_info.contract_no
	 * @param contractNo  the value for tf_loan_info.contract_no
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tf_loan_info.loan_no
	 * @return  the value of tf_loan_info.loan_no
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	public String getLoanNo() {
		return loanNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tf_loan_info.loan_no
	 * @param loanNo  the value for tf_loan_info.loan_no
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	public void setLoanNo(String loanNo) {
		this.loanNo = loanNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tf_loan_info.loan_amount
	 * @return  the value of tf_loan_info.loan_amount
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	public BigDecimal getLoanAmount() {
		return loanAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tf_loan_info.loan_amount
	 * @param loanAmount  the value for tf_loan_info.loan_amount
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	public void setLoanAmount(BigDecimal loanAmount) {
		this.loanAmount = loanAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tf_loan_info.loan_date
	 * @return  the value of tf_loan_info.loan_date
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	public Date getLoanDate() {
		return loanDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tf_loan_info.loan_date
	 * @param loanDate  the value for tf_loan_info.loan_date
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	public void setLoanDate(Date loanDate) {
		this.loanDate = loanDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tf_loan_info.loan_term
	 * @return  the value of tf_loan_info.loan_term
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	public Integer getLoanTerm() {
		return loanTerm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tf_loan_info.loan_term
	 * @param loanTerm  the value for tf_loan_info.loan_term
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	public void setLoanTerm(Integer loanTerm) {
		this.loanTerm = loanTerm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tf_loan_info.rate_id
	 * @return  the value of tf_loan_info.rate_id
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	public String getRateId() {
		return rateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tf_loan_info.rate_id
	 * @param rateId  the value for tf_loan_info.rate_id
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	public void setRateId(String rateId) {
		this.rateId = rateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tf_loan_info.create_time
	 * @return  the value of tf_loan_info.create_time
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tf_loan_info.create_time
	 * @param createTime  the value for tf_loan_info.create_time
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tf_loan_info.deposit_rate
	 * @return  the value of tf_loan_info.deposit_rate
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	public BigDecimal getDepositRate() {
		return depositRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tf_loan_info.deposit_rate
	 * @param depositRate  the value for tf_loan_info.deposit_rate
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	public void setDepositRate(BigDecimal depositRate) {
		this.depositRate = depositRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tf_loan_info.repay_status
	 * @return  the value of tf_loan_info.repay_status
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	public String getRepayStatus() {
		return repayStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tf_loan_info.repay_status
	 * @param repayStatus  the value for tf_loan_info.repay_status
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	public void setRepayStatus(String repayStatus) {
		this.repayStatus = repayStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tf_loan_info.interest_amount
	 * @return  the value of tf_loan_info.interest_amount
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	public BigDecimal getInterestAmount() {
		return interestAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tf_loan_info.interest_amount
	 * @param interestAmount  the value for tf_loan_info.interest_amount
	 * @mbggenerated  Fri Nov 24 10:17:21 CST 2017
	 */
	public void setInterestAmount(BigDecimal interestAmount) {
		this.interestAmount = interestAmount;
	}
}