package com.ut.scf.pojo.auto;

public class BusinessTypeInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_info.product_id
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	private String typeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_info.product_type
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	private String typeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_info.product_name
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	private String typeDescribe;
	
	
	
	public String getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_info.product_id
	 * @param productId  the value for product_info.product_id
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_info.product_type
	 * @return  the value of product_info.product_type
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	public String getTypeName() {
		return typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_info.product_type
	 * @param productType  the value for product_info.product_type
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_info.product_name
	 * @return  the value of product_info.product_name
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	public String getTypeDescribe() {
		return typeDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_info.product_name
	 * @param productName  the value for product_info.product_name
	 * @mbggenerated  Tue Jul 25 13:40:08 CST 2017
	 */
	public void setTypeDescribe(String typeDescribe) {
		this.typeDescribe = typeDescribe;
	}

	
}