package com.ut.scf.pojo.auto;

import java.util.Date;

public class DykYuqiFachebili {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyk_yuqi_fachebili.id
     *
     * @mbggenerated Wed Sep 12 10:19:13 GMT+08:00 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyk_yuqi_fachebili.fache_year
     *
     * @mbggenerated Wed Sep 12 10:19:13 GMT+08:00 2018
     */
    private String facheYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyk_yuqi_fachebili.fache_month
     *
     * @mbggenerated Wed Sep 12 10:19:13 GMT+08:00 2018
     */
    private String facheMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyk_yuqi_fachebili.ywlx_id
     *
     * @mbggenerated Wed Sep 12 10:19:13 GMT+08:00 2018
     */
    private String ywlxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyk_yuqi_fachebili.corp_id
     *
     * @mbggenerated Wed Sep 12 10:19:13 GMT+08:00 2018
     */
    private String corpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyk_yuqi_fachebili.fachebili
     *
     * @mbggenerated Wed Sep 12 10:19:13 GMT+08:00 2018
     */
    private String fachebili;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyk_yuqi_fachebili.czren
     *
     * @mbggenerated Wed Sep 12 10:19:13 GMT+08:00 2018
     */
    private String czren;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyk_yuqi_fachebili.czsj
     *
     * @mbggenerated Wed Sep 12 10:19:13 GMT+08:00 2018
     */
    private Date czsj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyk_yuqi_fachebili.id
     *
     * @return the value of dyk_yuqi_fachebili.id
     *
     * @mbggenerated Wed Sep 12 10:19:13 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyk_yuqi_fachebili.id
     *
     * @param id the value for dyk_yuqi_fachebili.id
     *
     * @mbggenerated Wed Sep 12 10:19:13 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyk_yuqi_fachebili.fache_year
     *
     * @return the value of dyk_yuqi_fachebili.fache_year
     *
     * @mbggenerated Wed Sep 12 10:19:13 GMT+08:00 2018
     */
    public String getFacheYear() {
        return facheYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyk_yuqi_fachebili.fache_year
     *
     * @param facheYear the value for dyk_yuqi_fachebili.fache_year
     *
     * @mbggenerated Wed Sep 12 10:19:13 GMT+08:00 2018
     */
    public void setFacheYear(String facheYear) {
        this.facheYear = facheYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyk_yuqi_fachebili.fache_month
     *
     * @return the value of dyk_yuqi_fachebili.fache_month
     *
     * @mbggenerated Wed Sep 12 10:19:13 GMT+08:00 2018
     */
    public String getFacheMonth() {
        return facheMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyk_yuqi_fachebili.fache_month
     *
     * @param facheMonth the value for dyk_yuqi_fachebili.fache_month
     *
     * @mbggenerated Wed Sep 12 10:19:13 GMT+08:00 2018
     */
    public void setFacheMonth(String facheMonth) {
        this.facheMonth = facheMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyk_yuqi_fachebili.ywlx_id
     *
     * @return the value of dyk_yuqi_fachebili.ywlx_id
     *
     * @mbggenerated Wed Sep 12 10:19:13 GMT+08:00 2018
     */
    public String getYwlxId() {
        return ywlxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyk_yuqi_fachebili.ywlx_id
     *
     * @param ywlxId the value for dyk_yuqi_fachebili.ywlx_id
     *
     * @mbggenerated Wed Sep 12 10:19:13 GMT+08:00 2018
     */
    public void setYwlxId(String ywlxId) {
        this.ywlxId = ywlxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyk_yuqi_fachebili.corp_id
     *
     * @return the value of dyk_yuqi_fachebili.corp_id
     *
     * @mbggenerated Wed Sep 12 10:19:13 GMT+08:00 2018
     */
    public String getCorpId() {
        return corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyk_yuqi_fachebili.corp_id
     *
     * @param corpId the value for dyk_yuqi_fachebili.corp_id
     *
     * @mbggenerated Wed Sep 12 10:19:13 GMT+08:00 2018
     */
    public void setCorpId(String corpId) {
        this.corpId = corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyk_yuqi_fachebili.fachebili
     *
     * @return the value of dyk_yuqi_fachebili.fachebili
     *
     * @mbggenerated Wed Sep 12 10:19:13 GMT+08:00 2018
     */
    public String getFachebili() {
        return fachebili;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyk_yuqi_fachebili.fachebili
     *
     * @param fachebili the value for dyk_yuqi_fachebili.fachebili
     *
     * @mbggenerated Wed Sep 12 10:19:13 GMT+08:00 2018
     */
    public void setFachebili(String fachebili) {
        this.fachebili = fachebili;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyk_yuqi_fachebili.czren
     *
     * @return the value of dyk_yuqi_fachebili.czren
     *
     * @mbggenerated Wed Sep 12 10:19:13 GMT+08:00 2018
     */
    public String getCzren() {
        return czren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyk_yuqi_fachebili.czren
     *
     * @param czren the value for dyk_yuqi_fachebili.czren
     *
     * @mbggenerated Wed Sep 12 10:19:13 GMT+08:00 2018
     */
    public void setCzren(String czren) {
        this.czren = czren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyk_yuqi_fachebili.czsj
     *
     * @return the value of dyk_yuqi_fachebili.czsj
     *
     * @mbggenerated Wed Sep 12 10:19:13 GMT+08:00 2018
     */
    public Date getCzsj() {
        return czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyk_yuqi_fachebili.czsj
     *
     * @param czsj the value for dyk_yuqi_fachebili.czsj
     *
     * @mbggenerated Wed Sep 12 10:19:13 GMT+08:00 2018
     */
    public void setCzsj(Date czsj) {
        this.czsj = czsj;
    }
}