package com.ut.scf.pojo.auto;

import java.math.BigDecimal;
import java.util.Date;

import com.ut.scf.reqbean.PageReqBean;

public class FinanceInfo extends PageReqBean{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.finance_id
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	private String financeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.apply_date
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	private Date applyDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.corp_id
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	private String corpId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.finance_rate
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	private BigDecimal financeRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.cash_rate
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	private BigDecimal cashRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.finance_start_date
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	private Date financeStartDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.finance_end_date
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	private Date financeEndDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.finance_amount
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	private BigDecimal financeAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.finance_balance
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	private BigDecimal financeBalance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.expense
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	private BigDecimal expense;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.finance_status
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	private String financeStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.pay_id
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	private String payId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.pay_date
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	private Date payDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.pay_amt
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	private BigDecimal payAmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.note
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	private String note;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column finance_info.product_id
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	private String productId;

	
	private String ywlxId;
	
	private String cprYear;
	
	private String cprMonth;
	
	private String uploadUrl;
	
	private String attachSize;
	
	private String fileUrl;
	
	private String attachType;
	
	private String templateUrl;
	private String templateUrlNew;
	private String fkTemplateUrl;
	private String fkTemplateUrlNew;
	//20180822新增字段
	private String firTime;
	private String secTime;
	
	private String corpSum;
	private String carSum;
	private String returnedSum;
	private String payAmtSum;
	private String bfb;
	
	private String ywlxId1;
	private String cprYear1;
	private String cprMonth1;
	private String corpSum1;
	private String carSum1;
	private String payAmtSum1;
	private String returnedSum1;
	private String bfb1;
	
	private BigDecimal payGuaranteeSum;
	private BigDecimal payAmitSum;
	private BigDecimal actRepayAmtSum;

	
	private String duifuDay;
	private BigDecimal payAmitSum1;
	
	
	
	
	public BigDecimal getPayAmitSum1() {
		return payAmitSum1;
	}

	public void setPayAmitSum1(BigDecimal payAmitSum1) {
		this.payAmitSum1 = payAmitSum1;
	}

	public String getDuifuDay() {
		return duifuDay;
	}

	public void setDuifuDay(String duifuDay) {
		this.duifuDay = duifuDay;
	}

	public BigDecimal getPayGuaranteeSum() {
		return payGuaranteeSum;
	}

	public void setPayGuaranteeSum(BigDecimal payGuaranteeSum) {
		this.payGuaranteeSum = payGuaranteeSum;
	}

	public BigDecimal getPayAmitSum() {
		return payAmitSum;
	}

	public void setPayAmitSum(BigDecimal payAmitSum) {
		this.payAmitSum = payAmitSum;
	}

	public BigDecimal getActRepayAmtSum() {
		return actRepayAmtSum;
	}

	public void setActRepayAmtSum(BigDecimal actRepayAmtSum) {
		this.actRepayAmtSum = actRepayAmtSum;
	}

	public String getReturnedSum() {
		return returnedSum;
	}

	public void setReturnedSum(String returnedSum) {
		this.returnedSum = returnedSum;
	}

	public String getReturnedSum1() {
		return returnedSum1;
	}

	public void setReturnedSum1(String returnedSum1) {
		this.returnedSum1 = returnedSum1;
	}

	public String getCarSum() {
		return carSum;
	}

	public void setCarSum(String carSum) {
		this.carSum = carSum;
	}

	public String getCarSum1() {
		return carSum1;
	}

	public void setCarSum1(String carSum1) {
		this.carSum1 = carSum1;
	}

	public String getFirTime() {
		return firTime;
	}

	public void setFirTime(String firTime) {
		this.firTime = firTime;
	}

	public String getSecTime() {
		return secTime;
	}

	public void setSecTime(String secTime) {
		this.secTime = secTime;
	}

	public String getCorpSum() {
		return corpSum;
	}

	public void setCorpSum(String corpSum) {
		this.corpSum = corpSum;
	}

	public String getPayAmtSum() {
		return payAmtSum;
	}

	public void setPayAmtSum(String payAmtSum) {
		this.payAmtSum = payAmtSum;
	}

	public String getBfb() {
		return bfb;
	}

	public void setBfb(String bfb) {
		this.bfb = bfb;
	}

	public String getYwlxId1() {
		return ywlxId1;
	}

	public void setYwlxId1(String ywlxId1) {
		this.ywlxId1 = ywlxId1;
	}

	public String getCprYear1() {
		return cprYear1;
	}

	public void setCprYear1(String cprYear1) {
		this.cprYear1 = cprYear1;
	}

	public String getCprMonth1() {
		return cprMonth1;
	}

	public void setCprMonth1(String cprMonth1) {
		this.cprMonth1 = cprMonth1;
	}

	public String getCorpSum1() {
		return corpSum1;
	}

	public void setCorpSum1(String corpSum1) {
		this.corpSum1 = corpSum1;
	}

	public String getPayAmtSum1() {
		return payAmtSum1;
	}

	public void setPayAmtSum1(String payAmtSum1) {
		this.payAmtSum1 = payAmtSum1;
	}

	public String getBfb1() {
		return bfb1;
	}

	public void setBfb1(String bfb1) {
		this.bfb1 = bfb1;
	}

	public String getAttachSize() {
		return attachSize;
	}

	public void setAttachSize(String attachSize) {
		this.attachSize = attachSize;
	}
	public String getFileUrl() {
		return fileUrl;
	}

	public void setFileUrl(String fileUrl) {
		this.fileUrl = fileUrl;
	}
	public String getAttachType() {
		return attachType;
	}

	public void setAttachType(String attachType) {
		this.attachType = attachType;
	}
	
	
	
	public String getYwlxId() {
		return ywlxId;
	}

	public void setYwlxId(String ywlxId) {
		this.ywlxId = ywlxId;
	}

	public void setCprYear(String cprYear) {
		this.cprYear = cprYear;
	}
	public String getCprYear() {
		return cprYear;
	}
	
	
	public String getCprMonth() {
		return cprMonth;
	}

	public void setCprMonth(String cprMonth) {
		this.cprMonth = cprMonth;
	}
	
	
	public String getUploadUrl() {
		return uploadUrl;
	}

	public void setUploadUrl(String uploadUrl) {
		this.uploadUrl = uploadUrl;
	}
	
	public String getTemplateUrl() {
		return templateUrl;
	}

	public void setTemplateUrl(String templateUrl) {
		this.templateUrl = templateUrl;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.finance_id
	 * @return  the value of finance_info.finance_id
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public String getFinanceId() {
		return financeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.finance_id
	 * @param financeId  the value for finance_info.finance_id
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public void setFinanceId(String financeId) {
		this.financeId = financeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.apply_date
	 * @return  the value of finance_info.apply_date
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public Date getApplyDate() {
		return applyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.apply_date
	 * @param applyDate  the value for finance_info.apply_date
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public void setApplyDate(Date applyDate) {
		this.applyDate = applyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.corp_id
	 * @return  the value of finance_info.corp_id
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public String getCorpId() {
		return corpId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.corp_id
	 * @param corpId  the value for finance_info.corp_id
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public void setCorpId(String corpId) {
		this.corpId = corpId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.finance_rate
	 * @return  the value of finance_info.finance_rate
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public BigDecimal getFinanceRate() {
		return financeRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.finance_rate
	 * @param financeRate  the value for finance_info.finance_rate
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public void setFinanceRate(BigDecimal financeRate) {
		this.financeRate = financeRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.cash_rate
	 * @return  the value of finance_info.cash_rate
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public BigDecimal getCashRate() {
		return cashRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.cash_rate
	 * @param cashRate  the value for finance_info.cash_rate
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public void setCashRate(BigDecimal cashRate) {
		this.cashRate = cashRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.finance_start_date
	 * @return  the value of finance_info.finance_start_date
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public Date getFinanceStartDate() {
		return financeStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.finance_start_date
	 * @param financeStartDate  the value for finance_info.finance_start_date
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public void setFinanceStartDate(Date financeStartDate) {
		this.financeStartDate = financeStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.finance_end_date
	 * @return  the value of finance_info.finance_end_date
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public Date getFinanceEndDate() {
		return financeEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.finance_end_date
	 * @param financeEndDate  the value for finance_info.finance_end_date
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public void setFinanceEndDate(Date financeEndDate) {
		this.financeEndDate = financeEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.finance_amount
	 * @return  the value of finance_info.finance_amount
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public BigDecimal getFinanceAmount() {
		return financeAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.finance_amount
	 * @param financeAmount  the value for finance_info.finance_amount
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public void setFinanceAmount(BigDecimal financeAmount) {
		this.financeAmount = financeAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.finance_balance
	 * @return  the value of finance_info.finance_balance
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public BigDecimal getFinanceBalance() {
		return financeBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.finance_balance
	 * @param financeBalance  the value for finance_info.finance_balance
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public void setFinanceBalance(BigDecimal financeBalance) {
		this.financeBalance = financeBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.expense
	 * @return  the value of finance_info.expense
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public BigDecimal getExpense() {
		return expense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.expense
	 * @param expense  the value for finance_info.expense
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public void setExpense(BigDecimal expense) {
		this.expense = expense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.finance_status
	 * @return  the value of finance_info.finance_status
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public String getFinanceStatus() {
		return financeStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.finance_status
	 * @param financeStatus  the value for finance_info.finance_status
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public void setFinanceStatus(String financeStatus) {
		this.financeStatus = financeStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.pay_id
	 * @return  the value of finance_info.pay_id
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public String getPayId() {
		return payId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.pay_id
	 * @param payId  the value for finance_info.pay_id
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public void setPayId(String payId) {
		this.payId = payId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.pay_date
	 * @return  the value of finance_info.pay_date
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public Date getPayDate() {
		return payDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.pay_date
	 * @param payDate  the value for finance_info.pay_date
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public void setPayDate(Date payDate) {
		this.payDate = payDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.pay_amt
	 * @return  the value of finance_info.pay_amt
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public BigDecimal getPayAmt() {
		return payAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.pay_amt
	 * @param payAmt  the value for finance_info.pay_amt
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public void setPayAmt(BigDecimal payAmt) {
		this.payAmt = payAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.note
	 * @return  the value of finance_info.note
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.note
	 * @param note  the value for finance_info.note
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column finance_info.product_id
	 * @return  the value of finance_info.product_id
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public String getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column finance_info.product_id
	 * @param productId  the value for finance_info.product_id
	 * @mbggenerated  Tue Jul 25 15:18:35 CST 2017
	 */
	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getTemplateUrlNew() {
		return templateUrlNew;
	}

	public void setTemplateUrlNew(String templateUrlNew) {
		this.templateUrlNew = templateUrlNew;
	}

	public String getFkTemplateUrl() {
		return fkTemplateUrl;
	}

	public void setFkTemplateUrl(String fkTemplateUrl) {
		this.fkTemplateUrl = fkTemplateUrl;
	}

	public String getFkTemplateUrlNew() {
		return fkTemplateUrlNew;
	}

	public void setFkTemplateUrlNew(String fkTemplateUrlNew) {
		this.fkTemplateUrlNew = fkTemplateUrlNew;
	}
}