package com.ut.scf.pojo.auto;

import java.math.BigDecimal;
import java.util.Date;

public class FqcrGuaranteeInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fqcr_guarantee_info.batch_id
     *
     * @mbg.generated Tue Jul 10 10:21:28 GMT+08:00 2018
     */
    private String batchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fqcr_guarantee_info.guarantee_money_rate
     *
     * @mbg.generated Tue Jul 10 10:21:28 GMT+08:00 2018
     */
    private BigDecimal guaranteeMoneyRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fqcr_guarantee_info.pay_able_guarantee
     *
     * @mbg.generated Tue Jul 10 10:21:28 GMT+08:00 2018
     */
    private BigDecimal payAbleGuarantee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fqcr_guarantee_info.guarantee_pay_date
     *
     * @mbg.generated Tue Jul 10 10:21:28 GMT+08:00 2018
     */
    private Date guaranteePayDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fqcr_guarantee_info.pay_act_guarantee
     *
     * @mbg.generated Tue Jul 10 10:21:28 GMT+08:00 2018
     */
    private BigDecimal payActGuarantee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fqcr_guarantee_info.guarantee_pay_his
     *
     * @mbg.generated Tue Jul 10 10:21:28 GMT+08:00 2018
     */
    private String guaranteePayHis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fqcr_guarantee_info.guarantee_balance
     *
     * @mbg.generated Tue Jul 10 10:21:28 GMT+08:00 2018
     */
    private BigDecimal guaranteeBalance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fqcr_guarantee_info.batch_id
     *
     * @return the value of fqcr_guarantee_info.batch_id
     *
     * @mbg.generated Tue Jul 10 10:21:28 GMT+08:00 2018
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fqcr_guarantee_info.batch_id
     *
     * @param batchId the value for fqcr_guarantee_info.batch_id
     *
     * @mbg.generated Tue Jul 10 10:21:28 GMT+08:00 2018
     */
    public void setBatchId(String batchId) {
        this.batchId = batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fqcr_guarantee_info.guarantee_money_rate
     *
     * @return the value of fqcr_guarantee_info.guarantee_money_rate
     *
     * @mbg.generated Tue Jul 10 10:21:28 GMT+08:00 2018
     */
    public BigDecimal getGuaranteeMoneyRate() {
        return guaranteeMoneyRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fqcr_guarantee_info.guarantee_money_rate
     *
     * @param guaranteeMoneyRate the value for fqcr_guarantee_info.guarantee_money_rate
     *
     * @mbg.generated Tue Jul 10 10:21:28 GMT+08:00 2018
     */
    public void setGuaranteeMoneyRate(BigDecimal guaranteeMoneyRate) {
        this.guaranteeMoneyRate = guaranteeMoneyRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fqcr_guarantee_info.pay_able_guarantee
     *
     * @return the value of fqcr_guarantee_info.pay_able_guarantee
     *
     * @mbg.generated Tue Jul 10 10:21:28 GMT+08:00 2018
     */
    public BigDecimal getPayAbleGuarantee() {
        return payAbleGuarantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fqcr_guarantee_info.pay_able_guarantee
     *
     * @param payAbleGuarantee the value for fqcr_guarantee_info.pay_able_guarantee
     *
     * @mbg.generated Tue Jul 10 10:21:28 GMT+08:00 2018
     */
    public void setPayAbleGuarantee(BigDecimal payAbleGuarantee) {
        this.payAbleGuarantee = payAbleGuarantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fqcr_guarantee_info.guarantee_pay_date
     *
     * @return the value of fqcr_guarantee_info.guarantee_pay_date
     *
     * @mbg.generated Tue Jul 10 10:21:28 GMT+08:00 2018
     */
    public Date getGuaranteePayDate() {
        return guaranteePayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fqcr_guarantee_info.guarantee_pay_date
     *
     * @param guaranteePayDate the value for fqcr_guarantee_info.guarantee_pay_date
     *
     * @mbg.generated Tue Jul 10 10:21:28 GMT+08:00 2018
     */
    public void setGuaranteePayDate(Date guaranteePayDate) {
        this.guaranteePayDate = guaranteePayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fqcr_guarantee_info.pay_act_guarantee
     *
     * @return the value of fqcr_guarantee_info.pay_act_guarantee
     *
     * @mbg.generated Tue Jul 10 10:21:28 GMT+08:00 2018
     */
    public BigDecimal getPayActGuarantee() {
        return payActGuarantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fqcr_guarantee_info.pay_act_guarantee
     *
     * @param payActGuarantee the value for fqcr_guarantee_info.pay_act_guarantee
     *
     * @mbg.generated Tue Jul 10 10:21:28 GMT+08:00 2018
     */
    public void setPayActGuarantee(BigDecimal payActGuarantee) {
        this.payActGuarantee = payActGuarantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fqcr_guarantee_info.guarantee_pay_his
     *
     * @return the value of fqcr_guarantee_info.guarantee_pay_his
     *
     * @mbg.generated Tue Jul 10 10:21:28 GMT+08:00 2018
     */
    public String getGuaranteePayHis() {
        return guaranteePayHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fqcr_guarantee_info.guarantee_pay_his
     *
     * @param guaranteePayHis the value for fqcr_guarantee_info.guarantee_pay_his
     *
     * @mbg.generated Tue Jul 10 10:21:28 GMT+08:00 2018
     */
    public void setGuaranteePayHis(String guaranteePayHis) {
        this.guaranteePayHis = guaranteePayHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fqcr_guarantee_info.guarantee_balance
     *
     * @return the value of fqcr_guarantee_info.guarantee_balance
     *
     * @mbg.generated Tue Jul 10 10:21:28 GMT+08:00 2018
     */
    public BigDecimal getGuaranteeBalance() {
        return guaranteeBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fqcr_guarantee_info.guarantee_balance
     *
     * @param guaranteeBalance the value for fqcr_guarantee_info.guarantee_balance
     *
     * @mbg.generated Tue Jul 10 10:21:28 GMT+08:00 2018
     */
    public void setGuaranteeBalance(BigDecimal guaranteeBalance) {
        this.guaranteeBalance = guaranteeBalance;
    }
}