package com.ut.scf.pojo.auto;

public class OrderAssetsInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_assets_info.id
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_assets_info.p_state
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    private String pState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_assets_info.p_people_type
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    private String pPeopleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_assets_info.p_order_begin
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    private String pOrderBegin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_assets_info.p_order_date
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    private String pOrderDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_assets_info.p_order_date_end
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    private String pOrderDateEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_assets_info.file_path
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    private String filePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_assets_info.id
     *
     * @return the value of order_assets_info.id
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_assets_info.id
     *
     * @param id the value for order_assets_info.id
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_assets_info.p_state
     *
     * @return the value of order_assets_info.p_state
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    public String getpState() {
        return pState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_assets_info.p_state
     *
     * @param pState the value for order_assets_info.p_state
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    public void setpState(String pState) {
        this.pState = pState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_assets_info.p_people_type
     *
     * @return the value of order_assets_info.p_people_type
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    public String getpPeopleType() {
        return pPeopleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_assets_info.p_people_type
     *
     * @param pPeopleType the value for order_assets_info.p_people_type
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    public void setpPeopleType(String pPeopleType) {
        this.pPeopleType = pPeopleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_assets_info.p_order_begin
     *
     * @return the value of order_assets_info.p_order_begin
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    public String getpOrderBegin() {
        return pOrderBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_assets_info.p_order_begin
     *
     * @param pOrderBegin the value for order_assets_info.p_order_begin
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    public void setpOrderBegin(String pOrderBegin) {
        this.pOrderBegin = pOrderBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_assets_info.p_order_date
     *
     * @return the value of order_assets_info.p_order_date
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    public String getpOrderDate() {
        return pOrderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_assets_info.p_order_date
     *
     * @param pOrderDate the value for order_assets_info.p_order_date
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    public void setpOrderDate(String pOrderDate) {
        this.pOrderDate = pOrderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_assets_info.p_order_date_end
     *
     * @return the value of order_assets_info.p_order_date_end
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    public String getpOrderDateEnd() {
        return pOrderDateEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_assets_info.p_order_date_end
     *
     * @param pOrderDateEnd the value for order_assets_info.p_order_date_end
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    public void setpOrderDateEnd(String pOrderDateEnd) {
        this.pOrderDateEnd = pOrderDateEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_assets_info.file_path
     *
     * @return the value of order_assets_info.file_path
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_assets_info.file_path
     *
     * @param filePath the value for order_assets_info.file_path
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }
}