package com.ut.scf.pojo.auto;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class RepaymentPlanUserUnInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    public RepaymentPlanUserUnInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andLoanTenorIsNull() {
            addCriterion("loan_tenor is null");
            return (Criteria) this;
        }

        public Criteria andLoanTenorIsNotNull() {
            addCriterion("loan_tenor is not null");
            return (Criteria) this;
        }

        public Criteria andLoanTenorEqualTo(Integer value) {
            addCriterion("loan_tenor =", value, "loanTenor");
            return (Criteria) this;
        }

        public Criteria andLoanTenorNotEqualTo(Integer value) {
            addCriterion("loan_tenor <>", value, "loanTenor");
            return (Criteria) this;
        }

        public Criteria andLoanTenorGreaterThan(Integer value) {
            addCriterion("loan_tenor >", value, "loanTenor");
            return (Criteria) this;
        }

        public Criteria andLoanTenorGreaterThanOrEqualTo(Integer value) {
            addCriterion("loan_tenor >=", value, "loanTenor");
            return (Criteria) this;
        }

        public Criteria andLoanTenorLessThan(Integer value) {
            addCriterion("loan_tenor <", value, "loanTenor");
            return (Criteria) this;
        }

        public Criteria andLoanTenorLessThanOrEqualTo(Integer value) {
            addCriterion("loan_tenor <=", value, "loanTenor");
            return (Criteria) this;
        }

        public Criteria andLoanTenorIn(List<Integer> values) {
            addCriterion("loan_tenor in", values, "loanTenor");
            return (Criteria) this;
        }

        public Criteria andLoanTenorNotIn(List<Integer> values) {
            addCriterion("loan_tenor not in", values, "loanTenor");
            return (Criteria) this;
        }

        public Criteria andLoanTenorBetween(Integer value1, Integer value2) {
            addCriterion("loan_tenor between", value1, value2, "loanTenor");
            return (Criteria) this;
        }

        public Criteria andLoanTenorNotBetween(Integer value1, Integer value2) {
            addCriterion("loan_tenor not between", value1, value2, "loanTenor");
            return (Criteria) this;
        }

        public Criteria andRepaymentPriceIsNull() {
            addCriterion("repayment_price is null");
            return (Criteria) this;
        }

        public Criteria andRepaymentPriceIsNotNull() {
            addCriterion("repayment_price is not null");
            return (Criteria) this;
        }

        public Criteria andRepaymentPriceEqualTo(BigDecimal value) {
            addCriterion("repayment_price =", value, "repaymentPrice");
            return (Criteria) this;
        }

        public Criteria andRepaymentPriceNotEqualTo(BigDecimal value) {
            addCriterion("repayment_price <>", value, "repaymentPrice");
            return (Criteria) this;
        }

        public Criteria andRepaymentPriceGreaterThan(BigDecimal value) {
            addCriterion("repayment_price >", value, "repaymentPrice");
            return (Criteria) this;
        }

        public Criteria andRepaymentPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("repayment_price >=", value, "repaymentPrice");
            return (Criteria) this;
        }

        public Criteria andRepaymentPriceLessThan(BigDecimal value) {
            addCriterion("repayment_price <", value, "repaymentPrice");
            return (Criteria) this;
        }

        public Criteria andRepaymentPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("repayment_price <=", value, "repaymentPrice");
            return (Criteria) this;
        }

        public Criteria andRepaymentPriceIn(List<BigDecimal> values) {
            addCriterion("repayment_price in", values, "repaymentPrice");
            return (Criteria) this;
        }

        public Criteria andRepaymentPriceNotIn(List<BigDecimal> values) {
            addCriterion("repayment_price not in", values, "repaymentPrice");
            return (Criteria) this;
        }

        public Criteria andRepaymentPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("repayment_price between", value1, value2, "repaymentPrice");
            return (Criteria) this;
        }

        public Criteria andRepaymentPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("repayment_price not between", value1, value2, "repaymentPrice");
            return (Criteria) this;
        }

        public Criteria andCommissionIsNull() {
            addCriterion("commission is null");
            return (Criteria) this;
        }

        public Criteria andCommissionIsNotNull() {
            addCriterion("commission is not null");
            return (Criteria) this;
        }

        public Criteria andCommissionEqualTo(BigDecimal value) {
            addCriterion("commission =", value, "commission");
            return (Criteria) this;
        }

        public Criteria andCommissionNotEqualTo(BigDecimal value) {
            addCriterion("commission <>", value, "commission");
            return (Criteria) this;
        }

        public Criteria andCommissionGreaterThan(BigDecimal value) {
            addCriterion("commission >", value, "commission");
            return (Criteria) this;
        }

        public Criteria andCommissionGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("commission >=", value, "commission");
            return (Criteria) this;
        }

        public Criteria andCommissionLessThan(BigDecimal value) {
            addCriterion("commission <", value, "commission");
            return (Criteria) this;
        }

        public Criteria andCommissionLessThanOrEqualTo(BigDecimal value) {
            addCriterion("commission <=", value, "commission");
            return (Criteria) this;
        }

        public Criteria andCommissionIn(List<BigDecimal> values) {
            addCriterion("commission in", values, "commission");
            return (Criteria) this;
        }

        public Criteria andCommissionNotIn(List<BigDecimal> values) {
            addCriterion("commission not in", values, "commission");
            return (Criteria) this;
        }

        public Criteria andCommissionBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("commission between", value1, value2, "commission");
            return (Criteria) this;
        }

        public Criteria andCommissionNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("commission not between", value1, value2, "commission");
            return (Criteria) this;
        }

        public Criteria andInsuranceIsNull() {
            addCriterion("insurance is null");
            return (Criteria) this;
        }

        public Criteria andInsuranceIsNotNull() {
            addCriterion("insurance is not null");
            return (Criteria) this;
        }

        public Criteria andInsuranceEqualTo(BigDecimal value) {
            addCriterion("insurance =", value, "insurance");
            return (Criteria) this;
        }

        public Criteria andInsuranceNotEqualTo(BigDecimal value) {
            addCriterion("insurance <>", value, "insurance");
            return (Criteria) this;
        }

        public Criteria andInsuranceGreaterThan(BigDecimal value) {
            addCriterion("insurance >", value, "insurance");
            return (Criteria) this;
        }

        public Criteria andInsuranceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("insurance >=", value, "insurance");
            return (Criteria) this;
        }

        public Criteria andInsuranceLessThan(BigDecimal value) {
            addCriterion("insurance <", value, "insurance");
            return (Criteria) this;
        }

        public Criteria andInsuranceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("insurance <=", value, "insurance");
            return (Criteria) this;
        }

        public Criteria andInsuranceIn(List<BigDecimal> values) {
            addCriterion("insurance in", values, "insurance");
            return (Criteria) this;
        }

        public Criteria andInsuranceNotIn(List<BigDecimal> values) {
            addCriterion("insurance not in", values, "insurance");
            return (Criteria) this;
        }

        public Criteria andInsuranceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("insurance between", value1, value2, "insurance");
            return (Criteria) this;
        }

        public Criteria andInsuranceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("insurance not between", value1, value2, "insurance");
            return (Criteria) this;
        }

        public Criteria andRepaymentDamagesIsNull() {
            addCriterion("repayment_damages is null");
            return (Criteria) this;
        }

        public Criteria andRepaymentDamagesIsNotNull() {
            addCriterion("repayment_damages is not null");
            return (Criteria) this;
        }

        public Criteria andRepaymentDamagesEqualTo(BigDecimal value) {
            addCriterion("repayment_damages =", value, "repaymentDamages");
            return (Criteria) this;
        }

        public Criteria andRepaymentDamagesNotEqualTo(BigDecimal value) {
            addCriterion("repayment_damages <>", value, "repaymentDamages");
            return (Criteria) this;
        }

        public Criteria andRepaymentDamagesGreaterThan(BigDecimal value) {
            addCriterion("repayment_damages >", value, "repaymentDamages");
            return (Criteria) this;
        }

        public Criteria andRepaymentDamagesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("repayment_damages >=", value, "repaymentDamages");
            return (Criteria) this;
        }

        public Criteria andRepaymentDamagesLessThan(BigDecimal value) {
            addCriterion("repayment_damages <", value, "repaymentDamages");
            return (Criteria) this;
        }

        public Criteria andRepaymentDamagesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("repayment_damages <=", value, "repaymentDamages");
            return (Criteria) this;
        }

        public Criteria andRepaymentDamagesIn(List<BigDecimal> values) {
            addCriterion("repayment_damages in", values, "repaymentDamages");
            return (Criteria) this;
        }

        public Criteria andRepaymentDamagesNotIn(List<BigDecimal> values) {
            addCriterion("repayment_damages not in", values, "repaymentDamages");
            return (Criteria) this;
        }

        public Criteria andRepaymentDamagesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("repayment_damages between", value1, value2, "repaymentDamages");
            return (Criteria) this;
        }

        public Criteria andRepaymentDamagesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("repayment_damages not between", value1, value2, "repaymentDamages");
            return (Criteria) this;
        }

        public Criteria andRepaymentDateIsNull() {
            addCriterion("repayment_date is null");
            return (Criteria) this;
        }

        public Criteria andRepaymentDateIsNotNull() {
            addCriterion("repayment_date is not null");
            return (Criteria) this;
        }

        public Criteria andRepaymentDateEqualTo(String value) {
            addCriterion("repayment_date =", value, "repaymentDate");
            return (Criteria) this;
        }

        public Criteria andRepaymentDateNotEqualTo(String value) {
            addCriterion("repayment_date <>", value, "repaymentDate");
            return (Criteria) this;
        }

        public Criteria andRepaymentDateGreaterThan(String value) {
            addCriterion("repayment_date >", value, "repaymentDate");
            return (Criteria) this;
        }

        public Criteria andRepaymentDateGreaterThanOrEqualTo(String value) {
            addCriterion("repayment_date >=", value, "repaymentDate");
            return (Criteria) this;
        }

        public Criteria andRepaymentDateLessThan(String value) {
            addCriterion("repayment_date <", value, "repaymentDate");
            return (Criteria) this;
        }

        public Criteria andRepaymentDateLessThanOrEqualTo(String value) {
            addCriterion("repayment_date <=", value, "repaymentDate");
            return (Criteria) this;
        }

        public Criteria andRepaymentDateLike(String value) {
            addCriterion("repayment_date like", value, "repaymentDate");
            return (Criteria) this;
        }

        public Criteria andRepaymentDateNotLike(String value) {
            addCriterion("repayment_date not like", value, "repaymentDate");
            return (Criteria) this;
        }

        public Criteria andRepaymentDateIn(List<String> values) {
            addCriterion("repayment_date in", values, "repaymentDate");
            return (Criteria) this;
        }

        public Criteria andRepaymentDateNotIn(List<String> values) {
            addCriterion("repayment_date not in", values, "repaymentDate");
            return (Criteria) this;
        }

        public Criteria andRepaymentDateBetween(String value1, String value2) {
            addCriterion("repayment_date between", value1, value2, "repaymentDate");
            return (Criteria) this;
        }

        public Criteria andRepaymentDateNotBetween(String value1, String value2) {
            addCriterion("repayment_date not between", value1, value2, "repaymentDate");
            return (Criteria) this;
        }

        public Criteria andPaidPriceIsNull() {
            addCriterion("paid_price is null");
            return (Criteria) this;
        }

        public Criteria andPaidPriceIsNotNull() {
            addCriterion("paid_price is not null");
            return (Criteria) this;
        }

        public Criteria andPaidPriceEqualTo(BigDecimal value) {
            addCriterion("paid_price =", value, "paidPrice");
            return (Criteria) this;
        }

        public Criteria andPaidPriceNotEqualTo(BigDecimal value) {
            addCriterion("paid_price <>", value, "paidPrice");
            return (Criteria) this;
        }

        public Criteria andPaidPriceGreaterThan(BigDecimal value) {
            addCriterion("paid_price >", value, "paidPrice");
            return (Criteria) this;
        }

        public Criteria andPaidPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("paid_price >=", value, "paidPrice");
            return (Criteria) this;
        }

        public Criteria andPaidPriceLessThan(BigDecimal value) {
            addCriterion("paid_price <", value, "paidPrice");
            return (Criteria) this;
        }

        public Criteria andPaidPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("paid_price <=", value, "paidPrice");
            return (Criteria) this;
        }

        public Criteria andPaidPriceIn(List<BigDecimal> values) {
            addCriterion("paid_price in", values, "paidPrice");
            return (Criteria) this;
        }

        public Criteria andPaidPriceNotIn(List<BigDecimal> values) {
            addCriterion("paid_price not in", values, "paidPrice");
            return (Criteria) this;
        }

        public Criteria andPaidPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("paid_price between", value1, value2, "paidPrice");
            return (Criteria) this;
        }

        public Criteria andPaidPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("paid_price not between", value1, value2, "paidPrice");
            return (Criteria) this;
        }

        public Criteria andPaidCommissionIsNull() {
            addCriterion("paid_commission is null");
            return (Criteria) this;
        }

        public Criteria andPaidCommissionIsNotNull() {
            addCriterion("paid_commission is not null");
            return (Criteria) this;
        }

        public Criteria andPaidCommissionEqualTo(BigDecimal value) {
            addCriterion("paid_commission =", value, "paidCommission");
            return (Criteria) this;
        }

        public Criteria andPaidCommissionNotEqualTo(BigDecimal value) {
            addCriterion("paid_commission <>", value, "paidCommission");
            return (Criteria) this;
        }

        public Criteria andPaidCommissionGreaterThan(BigDecimal value) {
            addCriterion("paid_commission >", value, "paidCommission");
            return (Criteria) this;
        }

        public Criteria andPaidCommissionGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("paid_commission >=", value, "paidCommission");
            return (Criteria) this;
        }

        public Criteria andPaidCommissionLessThan(BigDecimal value) {
            addCriterion("paid_commission <", value, "paidCommission");
            return (Criteria) this;
        }

        public Criteria andPaidCommissionLessThanOrEqualTo(BigDecimal value) {
            addCriterion("paid_commission <=", value, "paidCommission");
            return (Criteria) this;
        }

        public Criteria andPaidCommissionIn(List<BigDecimal> values) {
            addCriterion("paid_commission in", values, "paidCommission");
            return (Criteria) this;
        }

        public Criteria andPaidCommissionNotIn(List<BigDecimal> values) {
            addCriterion("paid_commission not in", values, "paidCommission");
            return (Criteria) this;
        }

        public Criteria andPaidCommissionBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("paid_commission between", value1, value2, "paidCommission");
            return (Criteria) this;
        }

        public Criteria andPaidCommissionNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("paid_commission not between", value1, value2, "paidCommission");
            return (Criteria) this;
        }

        public Criteria andPaidInsuranceIsNull() {
            addCriterion("paid_insurance is null");
            return (Criteria) this;
        }

        public Criteria andPaidInsuranceIsNotNull() {
            addCriterion("paid_insurance is not null");
            return (Criteria) this;
        }

        public Criteria andPaidInsuranceEqualTo(BigDecimal value) {
            addCriterion("paid_insurance =", value, "paidInsurance");
            return (Criteria) this;
        }

        public Criteria andPaidInsuranceNotEqualTo(BigDecimal value) {
            addCriterion("paid_insurance <>", value, "paidInsurance");
            return (Criteria) this;
        }

        public Criteria andPaidInsuranceGreaterThan(BigDecimal value) {
            addCriterion("paid_insurance >", value, "paidInsurance");
            return (Criteria) this;
        }

        public Criteria andPaidInsuranceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("paid_insurance >=", value, "paidInsurance");
            return (Criteria) this;
        }

        public Criteria andPaidInsuranceLessThan(BigDecimal value) {
            addCriterion("paid_insurance <", value, "paidInsurance");
            return (Criteria) this;
        }

        public Criteria andPaidInsuranceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("paid_insurance <=", value, "paidInsurance");
            return (Criteria) this;
        }

        public Criteria andPaidInsuranceIn(List<BigDecimal> values) {
            addCriterion("paid_insurance in", values, "paidInsurance");
            return (Criteria) this;
        }

        public Criteria andPaidInsuranceNotIn(List<BigDecimal> values) {
            addCriterion("paid_insurance not in", values, "paidInsurance");
            return (Criteria) this;
        }

        public Criteria andPaidInsuranceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("paid_insurance between", value1, value2, "paidInsurance");
            return (Criteria) this;
        }

        public Criteria andPaidInsuranceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("paid_insurance not between", value1, value2, "paidInsurance");
            return (Criteria) this;
        }

        public Criteria andPaidDamagesIsNull() {
            addCriterion("paid_damages is null");
            return (Criteria) this;
        }

        public Criteria andPaidDamagesIsNotNull() {
            addCriterion("paid_damages is not null");
            return (Criteria) this;
        }

        public Criteria andPaidDamagesEqualTo(BigDecimal value) {
            addCriterion("paid_damages =", value, "paidDamages");
            return (Criteria) this;
        }

        public Criteria andPaidDamagesNotEqualTo(BigDecimal value) {
            addCriterion("paid_damages <>", value, "paidDamages");
            return (Criteria) this;
        }

        public Criteria andPaidDamagesGreaterThan(BigDecimal value) {
            addCriterion("paid_damages >", value, "paidDamages");
            return (Criteria) this;
        }

        public Criteria andPaidDamagesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("paid_damages >=", value, "paidDamages");
            return (Criteria) this;
        }

        public Criteria andPaidDamagesLessThan(BigDecimal value) {
            addCriterion("paid_damages <", value, "paidDamages");
            return (Criteria) this;
        }

        public Criteria andPaidDamagesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("paid_damages <=", value, "paidDamages");
            return (Criteria) this;
        }

        public Criteria andPaidDamagesIn(List<BigDecimal> values) {
            addCriterion("paid_damages in", values, "paidDamages");
            return (Criteria) this;
        }

        public Criteria andPaidDamagesNotIn(List<BigDecimal> values) {
            addCriterion("paid_damages not in", values, "paidDamages");
            return (Criteria) this;
        }

        public Criteria andPaidDamagesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("paid_damages between", value1, value2, "paidDamages");
            return (Criteria) this;
        }

        public Criteria andPaidDamagesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("paid_damages not between", value1, value2, "paidDamages");
            return (Criteria) this;
        }

        public Criteria andPaidDateIsNull() {
            addCriterion("paid_date is null");
            return (Criteria) this;
        }

        public Criteria andPaidDateIsNotNull() {
            addCriterion("paid_date is not null");
            return (Criteria) this;
        }

        public Criteria andPaidDateEqualTo(String value) {
            addCriterion("paid_date =", value, "paidDate");
            return (Criteria) this;
        }

        public Criteria andPaidDateNotEqualTo(String value) {
            addCriterion("paid_date <>", value, "paidDate");
            return (Criteria) this;
        }

        public Criteria andPaidDateGreaterThan(String value) {
            addCriterion("paid_date >", value, "paidDate");
            return (Criteria) this;
        }

        public Criteria andPaidDateGreaterThanOrEqualTo(String value) {
            addCriterion("paid_date >=", value, "paidDate");
            return (Criteria) this;
        }

        public Criteria andPaidDateLessThan(String value) {
            addCriterion("paid_date <", value, "paidDate");
            return (Criteria) this;
        }

        public Criteria andPaidDateLessThanOrEqualTo(String value) {
            addCriterion("paid_date <=", value, "paidDate");
            return (Criteria) this;
        }

        public Criteria andPaidDateLike(String value) {
            addCriterion("paid_date like", value, "paidDate");
            return (Criteria) this;
        }

        public Criteria andPaidDateNotLike(String value) {
            addCriterion("paid_date not like", value, "paidDate");
            return (Criteria) this;
        }

        public Criteria andPaidDateIn(List<String> values) {
            addCriterion("paid_date in", values, "paidDate");
            return (Criteria) this;
        }

        public Criteria andPaidDateNotIn(List<String> values) {
            addCriterion("paid_date not in", values, "paidDate");
            return (Criteria) this;
        }

        public Criteria andPaidDateBetween(String value1, String value2) {
            addCriterion("paid_date between", value1, value2, "paidDate");
            return (Criteria) this;
        }

        public Criteria andPaidDateNotBetween(String value1, String value2) {
            addCriterion("paid_date not between", value1, value2, "paidDate");
            return (Criteria) this;
        }

        public Criteria andSystemtypeIsNull() {
            addCriterion("systemtype is null");
            return (Criteria) this;
        }

        public Criteria andSystemtypeIsNotNull() {
            addCriterion("systemtype is not null");
            return (Criteria) this;
        }

        public Criteria andSystemtypeEqualTo(Integer value) {
            addCriterion("systemtype =", value, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeNotEqualTo(Integer value) {
            addCriterion("systemtype <>", value, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeGreaterThan(Integer value) {
            addCriterion("systemtype >", value, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("systemtype >=", value, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeLessThan(Integer value) {
            addCriterion("systemtype <", value, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeLessThanOrEqualTo(Integer value) {
            addCriterion("systemtype <=", value, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeIn(List<Integer> values) {
            addCriterion("systemtype in", values, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeNotIn(List<Integer> values) {
            addCriterion("systemtype not in", values, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeBetween(Integer value1, Integer value2) {
            addCriterion("systemtype between", value1, value2, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeNotBetween(Integer value1, Integer value2) {
            addCriterion("systemtype not between", value1, value2, "systemtype");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andBatchIdIsNull() {
            addCriterion("batch_id is null");
            return (Criteria) this;
        }

        public Criteria andBatchIdIsNotNull() {
            addCriterion("batch_id is not null");
            return (Criteria) this;
        }

        public Criteria andBatchIdEqualTo(String value) {
            addCriterion("batch_id =", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdNotEqualTo(String value) {
            addCriterion("batch_id <>", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdGreaterThan(String value) {
            addCriterion("batch_id >", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdGreaterThanOrEqualTo(String value) {
            addCriterion("batch_id >=", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdLessThan(String value) {
            addCriterion("batch_id <", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdLessThanOrEqualTo(String value) {
            addCriterion("batch_id <=", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdLike(String value) {
            addCriterion("batch_id like", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdNotLike(String value) {
            addCriterion("batch_id not like", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdIn(List<String> values) {
            addCriterion("batch_id in", values, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdNotIn(List<String> values) {
            addCriterion("batch_id not in", values, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdBetween(String value1, String value2) {
            addCriterion("batch_id between", value1, value2, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdNotBetween(String value1, String value2) {
            addCriterion("batch_id not between", value1, value2, "batchId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdIsNull() {
            addCriterion("people_id is null");
            return (Criteria) this;
        }

        public Criteria andPeopleIdIsNotNull() {
            addCriterion("people_id is not null");
            return (Criteria) this;
        }

        public Criteria andPeopleIdEqualTo(Integer value) {
            addCriterion("people_id =", value, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdNotEqualTo(Integer value) {
            addCriterion("people_id <>", value, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdGreaterThan(Integer value) {
            addCriterion("people_id >", value, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("people_id >=", value, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdLessThan(Integer value) {
            addCriterion("people_id <", value, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdLessThanOrEqualTo(Integer value) {
            addCriterion("people_id <=", value, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdIn(List<Integer> values) {
            addCriterion("people_id in", values, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdNotIn(List<Integer> values) {
            addCriterion("people_id not in", values, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdBetween(Integer value1, Integer value2) {
            addCriterion("people_id between", value1, value2, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("people_id not between", value1, value2, "peopleId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated do_not_delete_during_merge Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}