package com.ut.scf.pojo.auto;

import java.util.ArrayList;
import java.util.List;

public class StuInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stu_info
     *
     * @mbg.generated Tue Jul 03 17:29:26 GMT+08:00 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stu_info
     *
     * @mbg.generated Tue Jul 03 17:29:26 GMT+08:00 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stu_info
     *
     * @mbg.generated Tue Jul 03 17:29:26 GMT+08:00 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbg.generated Tue Jul 03 17:29:26 GMT+08:00 2018
     */
    public StuInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbg.generated Tue Jul 03 17:29:26 GMT+08:00 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbg.generated Tue Jul 03 17:29:26 GMT+08:00 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbg.generated Tue Jul 03 17:29:26 GMT+08:00 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbg.generated Tue Jul 03 17:29:26 GMT+08:00 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbg.generated Tue Jul 03 17:29:26 GMT+08:00 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbg.generated Tue Jul 03 17:29:26 GMT+08:00 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbg.generated Tue Jul 03 17:29:26 GMT+08:00 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbg.generated Tue Jul 03 17:29:26 GMT+08:00 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbg.generated Tue Jul 03 17:29:26 GMT+08:00 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbg.generated Tue Jul 03 17:29:26 GMT+08:00 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stu_info
     *
     * @mbg.generated Tue Jul 03 17:29:26 GMT+08:00 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStuIdIsNull() {
            addCriterion("stu_id is null");
            return (Criteria) this;
        }

        public Criteria andStuIdIsNotNull() {
            addCriterion("stu_id is not null");
            return (Criteria) this;
        }

        public Criteria andStuIdEqualTo(String value) {
            addCriterion("stu_id =", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdNotEqualTo(String value) {
            addCriterion("stu_id <>", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdGreaterThan(String value) {
            addCriterion("stu_id >", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdGreaterThanOrEqualTo(String value) {
            addCriterion("stu_id >=", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdLessThan(String value) {
            addCriterion("stu_id <", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdLessThanOrEqualTo(String value) {
            addCriterion("stu_id <=", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdLike(String value) {
            addCriterion("stu_id like", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdNotLike(String value) {
            addCriterion("stu_id not like", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdIn(List<String> values) {
            addCriterion("stu_id in", values, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdNotIn(List<String> values) {
            addCriterion("stu_id not in", values, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdBetween(String value1, String value2) {
            addCriterion("stu_id between", value1, value2, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdNotBetween(String value1, String value2) {
            addCriterion("stu_id not between", value1, value2, "stuId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("age is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("age is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(Byte value) {
            addCriterion("age =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(Byte value) {
            addCriterion("age <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(Byte value) {
            addCriterion("age >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Byte value) {
            addCriterion("age >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(Byte value) {
            addCriterion("age <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(Byte value) {
            addCriterion("age <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<Byte> values) {
            addCriterion("age in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<Byte> values) {
            addCriterion("age not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(Byte value1, Byte value2) {
            addCriterion("age between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(Byte value1, Byte value2) {
            addCriterion("age not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andIdcardBirthdayIsNull() {
            addCriterion("idcard_birthday is null");
            return (Criteria) this;
        }

        public Criteria andIdcardBirthdayIsNotNull() {
            addCriterion("idcard_birthday is not null");
            return (Criteria) this;
        }

        public Criteria andIdcardBirthdayEqualTo(String value) {
            addCriterion("idcard_birthday =", value, "idcardBirthday");
            return (Criteria) this;
        }

        public Criteria andIdcardBirthdayNotEqualTo(String value) {
            addCriterion("idcard_birthday <>", value, "idcardBirthday");
            return (Criteria) this;
        }

        public Criteria andIdcardBirthdayGreaterThan(String value) {
            addCriterion("idcard_birthday >", value, "idcardBirthday");
            return (Criteria) this;
        }

        public Criteria andIdcardBirthdayGreaterThanOrEqualTo(String value) {
            addCriterion("idcard_birthday >=", value, "idcardBirthday");
            return (Criteria) this;
        }

        public Criteria andIdcardBirthdayLessThan(String value) {
            addCriterion("idcard_birthday <", value, "idcardBirthday");
            return (Criteria) this;
        }

        public Criteria andIdcardBirthdayLessThanOrEqualTo(String value) {
            addCriterion("idcard_birthday <=", value, "idcardBirthday");
            return (Criteria) this;
        }

        public Criteria andIdcardBirthdayLike(String value) {
            addCriterion("idcard_birthday like", value, "idcardBirthday");
            return (Criteria) this;
        }

        public Criteria andIdcardBirthdayNotLike(String value) {
            addCriterion("idcard_birthday not like", value, "idcardBirthday");
            return (Criteria) this;
        }

        public Criteria andIdcardBirthdayIn(List<String> values) {
            addCriterion("idcard_birthday in", values, "idcardBirthday");
            return (Criteria) this;
        }

        public Criteria andIdcardBirthdayNotIn(List<String> values) {
            addCriterion("idcard_birthday not in", values, "idcardBirthday");
            return (Criteria) this;
        }

        public Criteria andIdcardBirthdayBetween(String value1, String value2) {
            addCriterion("idcard_birthday between", value1, value2, "idcardBirthday");
            return (Criteria) this;
        }

        public Criteria andIdcardBirthdayNotBetween(String value1, String value2) {
            addCriterion("idcard_birthday not between", value1, value2, "idcardBirthday");
            return (Criteria) this;
        }

        public Criteria andIdCardIsNull() {
            addCriterion("id_card is null");
            return (Criteria) this;
        }

        public Criteria andIdCardIsNotNull() {
            addCriterion("id_card is not null");
            return (Criteria) this;
        }

        public Criteria andIdCardEqualTo(String value) {
            addCriterion("id_card =", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotEqualTo(String value) {
            addCriterion("id_card <>", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardGreaterThan(String value) {
            addCriterion("id_card >", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardGreaterThanOrEqualTo(String value) {
            addCriterion("id_card >=", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLessThan(String value) {
            addCriterion("id_card <", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLessThanOrEqualTo(String value) {
            addCriterion("id_card <=", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLike(String value) {
            addCriterion("id_card like", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotLike(String value) {
            addCriterion("id_card not like", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardIn(List<String> values) {
            addCriterion("id_card in", values, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotIn(List<String> values) {
            addCriterion("id_card not in", values, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardBetween(String value1, String value2) {
            addCriterion("id_card between", value1, value2, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotBetween(String value1, String value2) {
            addCriterion("id_card not between", value1, value2, "idCard");
            return (Criteria) this;
        }

        public Criteria andNationIsNull() {
            addCriterion("nation is null");
            return (Criteria) this;
        }

        public Criteria andNationIsNotNull() {
            addCriterion("nation is not null");
            return (Criteria) this;
        }

        public Criteria andNationEqualTo(String value) {
            addCriterion("nation =", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotEqualTo(String value) {
            addCriterion("nation <>", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationGreaterThan(String value) {
            addCriterion("nation >", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationGreaterThanOrEqualTo(String value) {
            addCriterion("nation >=", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationLessThan(String value) {
            addCriterion("nation <", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationLessThanOrEqualTo(String value) {
            addCriterion("nation <=", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationLike(String value) {
            addCriterion("nation like", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotLike(String value) {
            addCriterion("nation not like", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationIn(List<String> values) {
            addCriterion("nation in", values, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotIn(List<String> values) {
            addCriterion("nation not in", values, "nation");
            return (Criteria) this;
        }

        public Criteria andNationBetween(String value1, String value2) {
            addCriterion("nation between", value1, value2, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotBetween(String value1, String value2) {
            addCriterion("nation not between", value1, value2, "nation");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("mobile like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("mobile not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andTUnivsNameIsNull() {
            addCriterion("t_univs_name is null");
            return (Criteria) this;
        }

        public Criteria andTUnivsNameIsNotNull() {
            addCriterion("t_univs_name is not null");
            return (Criteria) this;
        }

        public Criteria andTUnivsNameEqualTo(String value) {
            addCriterion("t_univs_name =", value, "tUnivsName");
            return (Criteria) this;
        }

        public Criteria andTUnivsNameNotEqualTo(String value) {
            addCriterion("t_univs_name <>", value, "tUnivsName");
            return (Criteria) this;
        }

        public Criteria andTUnivsNameGreaterThan(String value) {
            addCriterion("t_univs_name >", value, "tUnivsName");
            return (Criteria) this;
        }

        public Criteria andTUnivsNameGreaterThanOrEqualTo(String value) {
            addCriterion("t_univs_name >=", value, "tUnivsName");
            return (Criteria) this;
        }

        public Criteria andTUnivsNameLessThan(String value) {
            addCriterion("t_univs_name <", value, "tUnivsName");
            return (Criteria) this;
        }

        public Criteria andTUnivsNameLessThanOrEqualTo(String value) {
            addCriterion("t_univs_name <=", value, "tUnivsName");
            return (Criteria) this;
        }

        public Criteria andTUnivsNameLike(String value) {
            addCriterion("t_univs_name like", value, "tUnivsName");
            return (Criteria) this;
        }

        public Criteria andTUnivsNameNotLike(String value) {
            addCriterion("t_univs_name not like", value, "tUnivsName");
            return (Criteria) this;
        }

        public Criteria andTUnivsNameIn(List<String> values) {
            addCriterion("t_univs_name in", values, "tUnivsName");
            return (Criteria) this;
        }

        public Criteria andTUnivsNameNotIn(List<String> values) {
            addCriterion("t_univs_name not in", values, "tUnivsName");
            return (Criteria) this;
        }

        public Criteria andTUnivsNameBetween(String value1, String value2) {
            addCriterion("t_univs_name between", value1, value2, "tUnivsName");
            return (Criteria) this;
        }

        public Criteria andTUnivsNameNotBetween(String value1, String value2) {
            addCriterion("t_univs_name not between", value1, value2, "tUnivsName");
            return (Criteria) this;
        }

        public Criteria andTUnivsGradeIsNull() {
            addCriterion("t_univs_grade is null");
            return (Criteria) this;
        }

        public Criteria andTUnivsGradeIsNotNull() {
            addCriterion("t_univs_grade is not null");
            return (Criteria) this;
        }

        public Criteria andTUnivsGradeEqualTo(String value) {
            addCriterion("t_univs_grade =", value, "tUnivsGrade");
            return (Criteria) this;
        }

        public Criteria andTUnivsGradeNotEqualTo(String value) {
            addCriterion("t_univs_grade <>", value, "tUnivsGrade");
            return (Criteria) this;
        }

        public Criteria andTUnivsGradeGreaterThan(String value) {
            addCriterion("t_univs_grade >", value, "tUnivsGrade");
            return (Criteria) this;
        }

        public Criteria andTUnivsGradeGreaterThanOrEqualTo(String value) {
            addCriterion("t_univs_grade >=", value, "tUnivsGrade");
            return (Criteria) this;
        }

        public Criteria andTUnivsGradeLessThan(String value) {
            addCriterion("t_univs_grade <", value, "tUnivsGrade");
            return (Criteria) this;
        }

        public Criteria andTUnivsGradeLessThanOrEqualTo(String value) {
            addCriterion("t_univs_grade <=", value, "tUnivsGrade");
            return (Criteria) this;
        }

        public Criteria andTUnivsGradeLike(String value) {
            addCriterion("t_univs_grade like", value, "tUnivsGrade");
            return (Criteria) this;
        }

        public Criteria andTUnivsGradeNotLike(String value) {
            addCriterion("t_univs_grade not like", value, "tUnivsGrade");
            return (Criteria) this;
        }

        public Criteria andTUnivsGradeIn(List<String> values) {
            addCriterion("t_univs_grade in", values, "tUnivsGrade");
            return (Criteria) this;
        }

        public Criteria andTUnivsGradeNotIn(List<String> values) {
            addCriterion("t_univs_grade not in", values, "tUnivsGrade");
            return (Criteria) this;
        }

        public Criteria andTUnivsGradeBetween(String value1, String value2) {
            addCriterion("t_univs_grade between", value1, value2, "tUnivsGrade");
            return (Criteria) this;
        }

        public Criteria andTUnivsGradeNotBetween(String value1, String value2) {
            addCriterion("t_univs_grade not between", value1, value2, "tUnivsGrade");
            return (Criteria) this;
        }

        public Criteria andTUnivsRoomIsNull() {
            addCriterion("t_univs_room is null");
            return (Criteria) this;
        }

        public Criteria andTUnivsRoomIsNotNull() {
            addCriterion("t_univs_room is not null");
            return (Criteria) this;
        }

        public Criteria andTUnivsRoomEqualTo(String value) {
            addCriterion("t_univs_room =", value, "tUnivsRoom");
            return (Criteria) this;
        }

        public Criteria andTUnivsRoomNotEqualTo(String value) {
            addCriterion("t_univs_room <>", value, "tUnivsRoom");
            return (Criteria) this;
        }

        public Criteria andTUnivsRoomGreaterThan(String value) {
            addCriterion("t_univs_room >", value, "tUnivsRoom");
            return (Criteria) this;
        }

        public Criteria andTUnivsRoomGreaterThanOrEqualTo(String value) {
            addCriterion("t_univs_room >=", value, "tUnivsRoom");
            return (Criteria) this;
        }

        public Criteria andTUnivsRoomLessThan(String value) {
            addCriterion("t_univs_room <", value, "tUnivsRoom");
            return (Criteria) this;
        }

        public Criteria andTUnivsRoomLessThanOrEqualTo(String value) {
            addCriterion("t_univs_room <=", value, "tUnivsRoom");
            return (Criteria) this;
        }

        public Criteria andTUnivsRoomLike(String value) {
            addCriterion("t_univs_room like", value, "tUnivsRoom");
            return (Criteria) this;
        }

        public Criteria andTUnivsRoomNotLike(String value) {
            addCriterion("t_univs_room not like", value, "tUnivsRoom");
            return (Criteria) this;
        }

        public Criteria andTUnivsRoomIn(List<String> values) {
            addCriterion("t_univs_room in", values, "tUnivsRoom");
            return (Criteria) this;
        }

        public Criteria andTUnivsRoomNotIn(List<String> values) {
            addCriterion("t_univs_room not in", values, "tUnivsRoom");
            return (Criteria) this;
        }

        public Criteria andTUnivsRoomBetween(String value1, String value2) {
            addCriterion("t_univs_room between", value1, value2, "tUnivsRoom");
            return (Criteria) this;
        }

        public Criteria andTUnivsRoomNotBetween(String value1, String value2) {
            addCriterion("t_univs_room not between", value1, value2, "tUnivsRoom");
            return (Criteria) this;
        }

        public Criteria andTUnivsFinishtimeIsNull() {
            addCriterion("t_univs_finishtime is null");
            return (Criteria) this;
        }

        public Criteria andTUnivsFinishtimeIsNotNull() {
            addCriterion("t_univs_finishtime is not null");
            return (Criteria) this;
        }

        public Criteria andTUnivsFinishtimeEqualTo(String value) {
            addCriterion("t_univs_finishtime =", value, "tUnivsFinishtime");
            return (Criteria) this;
        }

        public Criteria andTUnivsFinishtimeNotEqualTo(String value) {
            addCriterion("t_univs_finishtime <>", value, "tUnivsFinishtime");
            return (Criteria) this;
        }

        public Criteria andTUnivsFinishtimeGreaterThan(String value) {
            addCriterion("t_univs_finishtime >", value, "tUnivsFinishtime");
            return (Criteria) this;
        }

        public Criteria andTUnivsFinishtimeGreaterThanOrEqualTo(String value) {
            addCriterion("t_univs_finishtime >=", value, "tUnivsFinishtime");
            return (Criteria) this;
        }

        public Criteria andTUnivsFinishtimeLessThan(String value) {
            addCriterion("t_univs_finishtime <", value, "tUnivsFinishtime");
            return (Criteria) this;
        }

        public Criteria andTUnivsFinishtimeLessThanOrEqualTo(String value) {
            addCriterion("t_univs_finishtime <=", value, "tUnivsFinishtime");
            return (Criteria) this;
        }

        public Criteria andTUnivsFinishtimeLike(String value) {
            addCriterion("t_univs_finishtime like", value, "tUnivsFinishtime");
            return (Criteria) this;
        }

        public Criteria andTUnivsFinishtimeNotLike(String value) {
            addCriterion("t_univs_finishtime not like", value, "tUnivsFinishtime");
            return (Criteria) this;
        }

        public Criteria andTUnivsFinishtimeIn(List<String> values) {
            addCriterion("t_univs_finishtime in", values, "tUnivsFinishtime");
            return (Criteria) this;
        }

        public Criteria andTUnivsFinishtimeNotIn(List<String> values) {
            addCriterion("t_univs_finishtime not in", values, "tUnivsFinishtime");
            return (Criteria) this;
        }

        public Criteria andTUnivsFinishtimeBetween(String value1, String value2) {
            addCriterion("t_univs_finishtime between", value1, value2, "tUnivsFinishtime");
            return (Criteria) this;
        }

        public Criteria andTUnivsFinishtimeNotBetween(String value1, String value2) {
            addCriterion("t_univs_finishtime not between", value1, value2, "tUnivsFinishtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stu_info
     *
     * @mbg.generated do_not_delete_during_merge Tue Jul 03 17:29:26 GMT+08:00 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stu_info
     *
     * @mbg.generated Tue Jul 03 17:29:26 GMT+08:00 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}