package com.ut.scf.pojo.auto;

public class SupplierInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_info.corp_id
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    private String corpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_info.corp_name
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    private String corpName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_info.agency_num
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    private String agencyNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_info.fixed_phone
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    private String fixedPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_info.sys_type
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    private String sysType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_info.location_province
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    private String locationProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_info.location_city
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    private String locationCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_info.location_area
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    private String locationArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_info.location_address
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    private String locationAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_info.register_province
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    private String registerProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_info.register_city
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    private String registerCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_info.register_area
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    private String registerArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_info.register_address
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    private String registerAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_info.email
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_info.unfiorm_credit_code
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    private String unfiormCreditCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_info.legal_person
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    private String legalPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_info.cellphone
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    private String cellphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_info.id_number
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    private String idNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_info.business_license_pic
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    private String businessLicensePic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_info.corp_consitution_doc
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    private String corpConsitutionDoc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_info.corp_id
     *
     * @return the value of supplier_info.corp_id
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public String getCorpId() {
        return corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_info.corp_id
     *
     * @param corpId the value for supplier_info.corp_id
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public void setCorpId(String corpId) {
        this.corpId = corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_info.corp_name
     *
     * @return the value of supplier_info.corp_name
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public String getCorpName() {
        return corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_info.corp_name
     *
     * @param corpName the value for supplier_info.corp_name
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public void setCorpName(String corpName) {
        this.corpName = corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_info.agency_num
     *
     * @return the value of supplier_info.agency_num
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public String getAgencyNum() {
        return agencyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_info.agency_num
     *
     * @param agencyNum the value for supplier_info.agency_num
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public void setAgencyNum(String agencyNum) {
        this.agencyNum = agencyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_info.fixed_phone
     *
     * @return the value of supplier_info.fixed_phone
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public String getFixedPhone() {
        return fixedPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_info.fixed_phone
     *
     * @param fixedPhone the value for supplier_info.fixed_phone
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public void setFixedPhone(String fixedPhone) {
        this.fixedPhone = fixedPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_info.sys_type
     *
     * @return the value of supplier_info.sys_type
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public String getSysType() {
        return sysType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_info.sys_type
     *
     * @param sysType the value for supplier_info.sys_type
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public void setSysType(String sysType) {
        this.sysType = sysType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_info.location_province
     *
     * @return the value of supplier_info.location_province
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public String getLocationProvince() {
        return locationProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_info.location_province
     *
     * @param locationProvince the value for supplier_info.location_province
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public void setLocationProvince(String locationProvince) {
        this.locationProvince = locationProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_info.location_city
     *
     * @return the value of supplier_info.location_city
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public String getLocationCity() {
        return locationCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_info.location_city
     *
     * @param locationCity the value for supplier_info.location_city
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public void setLocationCity(String locationCity) {
        this.locationCity = locationCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_info.location_area
     *
     * @return the value of supplier_info.location_area
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public String getLocationArea() {
        return locationArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_info.location_area
     *
     * @param locationArea the value for supplier_info.location_area
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public void setLocationArea(String locationArea) {
        this.locationArea = locationArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_info.location_address
     *
     * @return the value of supplier_info.location_address
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public String getLocationAddress() {
        return locationAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_info.location_address
     *
     * @param locationAddress the value for supplier_info.location_address
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public void setLocationAddress(String locationAddress) {
        this.locationAddress = locationAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_info.register_province
     *
     * @return the value of supplier_info.register_province
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public String getRegisterProvince() {
        return registerProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_info.register_province
     *
     * @param registerProvince the value for supplier_info.register_province
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public void setRegisterProvince(String registerProvince) {
        this.registerProvince = registerProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_info.register_city
     *
     * @return the value of supplier_info.register_city
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public String getRegisterCity() {
        return registerCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_info.register_city
     *
     * @param registerCity the value for supplier_info.register_city
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public void setRegisterCity(String registerCity) {
        this.registerCity = registerCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_info.register_area
     *
     * @return the value of supplier_info.register_area
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public String getRegisterArea() {
        return registerArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_info.register_area
     *
     * @param registerArea the value for supplier_info.register_area
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public void setRegisterArea(String registerArea) {
        this.registerArea = registerArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_info.register_address
     *
     * @return the value of supplier_info.register_address
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public String getRegisterAddress() {
        return registerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_info.register_address
     *
     * @param registerAddress the value for supplier_info.register_address
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public void setRegisterAddress(String registerAddress) {
        this.registerAddress = registerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_info.email
     *
     * @return the value of supplier_info.email
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_info.email
     *
     * @param email the value for supplier_info.email
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_info.unfiorm_credit_code
     *
     * @return the value of supplier_info.unfiorm_credit_code
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public String getUnfiormCreditCode() {
        return unfiormCreditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_info.unfiorm_credit_code
     *
     * @param unfiormCreditCode the value for supplier_info.unfiorm_credit_code
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public void setUnfiormCreditCode(String unfiormCreditCode) {
        this.unfiormCreditCode = unfiormCreditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_info.legal_person
     *
     * @return the value of supplier_info.legal_person
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public String getLegalPerson() {
        return legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_info.legal_person
     *
     * @param legalPerson the value for supplier_info.legal_person
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public void setLegalPerson(String legalPerson) {
        this.legalPerson = legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_info.cellphone
     *
     * @return the value of supplier_info.cellphone
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public String getCellphone() {
        return cellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_info.cellphone
     *
     * @param cellphone the value for supplier_info.cellphone
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public void setCellphone(String cellphone) {
        this.cellphone = cellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_info.id_number
     *
     * @return the value of supplier_info.id_number
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_info.id_number
     *
     * @param idNumber the value for supplier_info.id_number
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_info.business_license_pic
     *
     * @return the value of supplier_info.business_license_pic
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public String getBusinessLicensePic() {
        return businessLicensePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_info.business_license_pic
     *
     * @param businessLicensePic the value for supplier_info.business_license_pic
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public void setBusinessLicensePic(String businessLicensePic) {
        this.businessLicensePic = businessLicensePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_info.corp_consitution_doc
     *
     * @return the value of supplier_info.corp_consitution_doc
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public String getCorpConsitutionDoc() {
        return corpConsitutionDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_info.corp_consitution_doc
     *
     * @param corpConsitutionDoc the value for supplier_info.corp_consitution_doc
     *
     * @mbg.generated Thu Oct 11 16:35:50 GMT+08:00 2018
     */
    public void setCorpConsitutionDoc(String corpConsitutionDoc) {
        this.corpConsitutionDoc = corpConsitutionDoc;
    }
}