package com.ut.scf.pojo.auto;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class SupplierInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplier_info
     *
     * @mbg.generated Sun Oct 14 03:46:43 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplier_info
     *
     * @mbg.generated Sun Oct 14 03:46:43 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplier_info
     *
     * @mbg.generated Sun Oct 14 03:46:43 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_info
     *
     * @mbg.generated Sun Oct 14 03:46:43 CST 2018
     */
    public SupplierInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_info
     *
     * @mbg.generated Sun Oct 14 03:46:43 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_info
     *
     * @mbg.generated Sun Oct 14 03:46:43 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_info
     *
     * @mbg.generated Sun Oct 14 03:46:43 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_info
     *
     * @mbg.generated Sun Oct 14 03:46:43 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_info
     *
     * @mbg.generated Sun Oct 14 03:46:43 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_info
     *
     * @mbg.generated Sun Oct 14 03:46:43 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_info
     *
     * @mbg.generated Sun Oct 14 03:46:43 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_info
     *
     * @mbg.generated Sun Oct 14 03:46:43 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_info
     *
     * @mbg.generated Sun Oct 14 03:46:43 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_info
     *
     * @mbg.generated Sun Oct 14 03:46:43 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table supplier_info
     *
     * @mbg.generated Sun Oct 14 03:46:43 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andCorpIdIsNull() {
            addCriterion("corp_id is null");
            return (Criteria) this;
        }

        public Criteria andCorpIdIsNotNull() {
            addCriterion("corp_id is not null");
            return (Criteria) this;
        }

        public Criteria andCorpIdEqualTo(String value) {
            addCriterion("corp_id =", value, "corpId");
            return (Criteria) this;
        }

        public Criteria andCorpIdNotEqualTo(String value) {
            addCriterion("corp_id <>", value, "corpId");
            return (Criteria) this;
        }

        public Criteria andCorpIdGreaterThan(String value) {
            addCriterion("corp_id >", value, "corpId");
            return (Criteria) this;
        }

        public Criteria andCorpIdGreaterThanOrEqualTo(String value) {
            addCriterion("corp_id >=", value, "corpId");
            return (Criteria) this;
        }

        public Criteria andCorpIdLessThan(String value) {
            addCriterion("corp_id <", value, "corpId");
            return (Criteria) this;
        }

        public Criteria andCorpIdLessThanOrEqualTo(String value) {
            addCriterion("corp_id <=", value, "corpId");
            return (Criteria) this;
        }

        public Criteria andCorpIdLike(String value) {
            addCriterion("corp_id like", value, "corpId");
            return (Criteria) this;
        }

        public Criteria andCorpIdNotLike(String value) {
            addCriterion("corp_id not like", value, "corpId");
            return (Criteria) this;
        }

        public Criteria andCorpIdIn(List<String> values) {
            addCriterion("corp_id in", values, "corpId");
            return (Criteria) this;
        }

        public Criteria andCorpIdNotIn(List<String> values) {
            addCriterion("corp_id not in", values, "corpId");
            return (Criteria) this;
        }

        public Criteria andCorpIdBetween(String value1, String value2) {
            addCriterion("corp_id between", value1, value2, "corpId");
            return (Criteria) this;
        }

        public Criteria andCorpIdNotBetween(String value1, String value2) {
            addCriterion("corp_id not between", value1, value2, "corpId");
            return (Criteria) this;
        }

        public Criteria andCorpNameIsNull() {
            addCriterion("corp_name is null");
            return (Criteria) this;
        }

        public Criteria andCorpNameIsNotNull() {
            addCriterion("corp_name is not null");
            return (Criteria) this;
        }

        public Criteria andCorpNameEqualTo(String value) {
            addCriterion("corp_name =", value, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameNotEqualTo(String value) {
            addCriterion("corp_name <>", value, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameGreaterThan(String value) {
            addCriterion("corp_name >", value, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameGreaterThanOrEqualTo(String value) {
            addCriterion("corp_name >=", value, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameLessThan(String value) {
            addCriterion("corp_name <", value, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameLessThanOrEqualTo(String value) {
            addCriterion("corp_name <=", value, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameLike(String value) {
            addCriterion("corp_name like", value, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameNotLike(String value) {
            addCriterion("corp_name not like", value, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameIn(List<String> values) {
            addCriterion("corp_name in", values, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameNotIn(List<String> values) {
            addCriterion("corp_name not in", values, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameBetween(String value1, String value2) {
            addCriterion("corp_name between", value1, value2, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameNotBetween(String value1, String value2) {
            addCriterion("corp_name not between", value1, value2, "corpName");
            return (Criteria) this;
        }

        public Criteria andAgencyNumIsNull() {
            addCriterion("agency_num is null");
            return (Criteria) this;
        }

        public Criteria andAgencyNumIsNotNull() {
            addCriterion("agency_num is not null");
            return (Criteria) this;
        }

        public Criteria andAgencyNumEqualTo(String value) {
            addCriterion("agency_num =", value, "agencyNum");
            return (Criteria) this;
        }

        public Criteria andAgencyNumNotEqualTo(String value) {
            addCriterion("agency_num <>", value, "agencyNum");
            return (Criteria) this;
        }

        public Criteria andAgencyNumGreaterThan(String value) {
            addCriterion("agency_num >", value, "agencyNum");
            return (Criteria) this;
        }

        public Criteria andAgencyNumGreaterThanOrEqualTo(String value) {
            addCriterion("agency_num >=", value, "agencyNum");
            return (Criteria) this;
        }

        public Criteria andAgencyNumLessThan(String value) {
            addCriterion("agency_num <", value, "agencyNum");
            return (Criteria) this;
        }

        public Criteria andAgencyNumLessThanOrEqualTo(String value) {
            addCriterion("agency_num <=", value, "agencyNum");
            return (Criteria) this;
        }

        public Criteria andAgencyNumLike(String value) {
            addCriterion("agency_num like", value, "agencyNum");
            return (Criteria) this;
        }

        public Criteria andAgencyNumNotLike(String value) {
            addCriterion("agency_num not like", value, "agencyNum");
            return (Criteria) this;
        }

        public Criteria andAgencyNumIn(List<String> values) {
            addCriterion("agency_num in", values, "agencyNum");
            return (Criteria) this;
        }

        public Criteria andAgencyNumNotIn(List<String> values) {
            addCriterion("agency_num not in", values, "agencyNum");
            return (Criteria) this;
        }

        public Criteria andAgencyNumBetween(String value1, String value2) {
            addCriterion("agency_num between", value1, value2, "agencyNum");
            return (Criteria) this;
        }

        public Criteria andAgencyNumNotBetween(String value1, String value2) {
            addCriterion("agency_num not between", value1, value2, "agencyNum");
            return (Criteria) this;
        }

        public Criteria andFixedPhoneIsNull() {
            addCriterion("fixed_phone is null");
            return (Criteria) this;
        }

        public Criteria andFixedPhoneIsNotNull() {
            addCriterion("fixed_phone is not null");
            return (Criteria) this;
        }

        public Criteria andFixedPhoneEqualTo(String value) {
            addCriterion("fixed_phone =", value, "fixedPhone");
            return (Criteria) this;
        }

        public Criteria andFixedPhoneNotEqualTo(String value) {
            addCriterion("fixed_phone <>", value, "fixedPhone");
            return (Criteria) this;
        }

        public Criteria andFixedPhoneGreaterThan(String value) {
            addCriterion("fixed_phone >", value, "fixedPhone");
            return (Criteria) this;
        }

        public Criteria andFixedPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("fixed_phone >=", value, "fixedPhone");
            return (Criteria) this;
        }

        public Criteria andFixedPhoneLessThan(String value) {
            addCriterion("fixed_phone <", value, "fixedPhone");
            return (Criteria) this;
        }

        public Criteria andFixedPhoneLessThanOrEqualTo(String value) {
            addCriterion("fixed_phone <=", value, "fixedPhone");
            return (Criteria) this;
        }

        public Criteria andFixedPhoneLike(String value) {
            addCriterion("fixed_phone like", value, "fixedPhone");
            return (Criteria) this;
        }

        public Criteria andFixedPhoneNotLike(String value) {
            addCriterion("fixed_phone not like", value, "fixedPhone");
            return (Criteria) this;
        }

        public Criteria andFixedPhoneIn(List<String> values) {
            addCriterion("fixed_phone in", values, "fixedPhone");
            return (Criteria) this;
        }

        public Criteria andFixedPhoneNotIn(List<String> values) {
            addCriterion("fixed_phone not in", values, "fixedPhone");
            return (Criteria) this;
        }

        public Criteria andFixedPhoneBetween(String value1, String value2) {
            addCriterion("fixed_phone between", value1, value2, "fixedPhone");
            return (Criteria) this;
        }

        public Criteria andFixedPhoneNotBetween(String value1, String value2) {
            addCriterion("fixed_phone not between", value1, value2, "fixedPhone");
            return (Criteria) this;
        }

        public Criteria andSysTypeIsNull() {
            addCriterion("sys_type is null");
            return (Criteria) this;
        }

        public Criteria andSysTypeIsNotNull() {
            addCriterion("sys_type is not null");
            return (Criteria) this;
        }

        public Criteria andSysTypeEqualTo(String value) {
            addCriterion("sys_type =", value, "sysType");
            return (Criteria) this;
        }

        public Criteria andSysTypeNotEqualTo(String value) {
            addCriterion("sys_type <>", value, "sysType");
            return (Criteria) this;
        }

        public Criteria andSysTypeGreaterThan(String value) {
            addCriterion("sys_type >", value, "sysType");
            return (Criteria) this;
        }

        public Criteria andSysTypeGreaterThanOrEqualTo(String value) {
            addCriterion("sys_type >=", value, "sysType");
            return (Criteria) this;
        }

        public Criteria andSysTypeLessThan(String value) {
            addCriterion("sys_type <", value, "sysType");
            return (Criteria) this;
        }

        public Criteria andSysTypeLessThanOrEqualTo(String value) {
            addCriterion("sys_type <=", value, "sysType");
            return (Criteria) this;
        }

        public Criteria andSysTypeLike(String value) {
            addCriterion("sys_type like", value, "sysType");
            return (Criteria) this;
        }

        public Criteria andSysTypeNotLike(String value) {
            addCriterion("sys_type not like", value, "sysType");
            return (Criteria) this;
        }

        public Criteria andSysTypeIn(List<String> values) {
            addCriterion("sys_type in", values, "sysType");
            return (Criteria) this;
        }

        public Criteria andSysTypeNotIn(List<String> values) {
            addCriterion("sys_type not in", values, "sysType");
            return (Criteria) this;
        }

        public Criteria andSysTypeBetween(String value1, String value2) {
            addCriterion("sys_type between", value1, value2, "sysType");
            return (Criteria) this;
        }

        public Criteria andSysTypeNotBetween(String value1, String value2) {
            addCriterion("sys_type not between", value1, value2, "sysType");
            return (Criteria) this;
        }

        public Criteria andLocationProvinceIsNull() {
            addCriterion("location_province is null");
            return (Criteria) this;
        }

        public Criteria andLocationProvinceIsNotNull() {
            addCriterion("location_province is not null");
            return (Criteria) this;
        }

        public Criteria andLocationProvinceEqualTo(String value) {
            addCriterion("location_province =", value, "locationProvince");
            return (Criteria) this;
        }

        public Criteria andLocationProvinceNotEqualTo(String value) {
            addCriterion("location_province <>", value, "locationProvince");
            return (Criteria) this;
        }

        public Criteria andLocationProvinceGreaterThan(String value) {
            addCriterion("location_province >", value, "locationProvince");
            return (Criteria) this;
        }

        public Criteria andLocationProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("location_province >=", value, "locationProvince");
            return (Criteria) this;
        }

        public Criteria andLocationProvinceLessThan(String value) {
            addCriterion("location_province <", value, "locationProvince");
            return (Criteria) this;
        }

        public Criteria andLocationProvinceLessThanOrEqualTo(String value) {
            addCriterion("location_province <=", value, "locationProvince");
            return (Criteria) this;
        }

        public Criteria andLocationProvinceLike(String value) {
            addCriterion("location_province like", value, "locationProvince");
            return (Criteria) this;
        }

        public Criteria andLocationProvinceNotLike(String value) {
            addCriterion("location_province not like", value, "locationProvince");
            return (Criteria) this;
        }

        public Criteria andLocationProvinceIn(List<String> values) {
            addCriterion("location_province in", values, "locationProvince");
            return (Criteria) this;
        }

        public Criteria andLocationProvinceNotIn(List<String> values) {
            addCriterion("location_province not in", values, "locationProvince");
            return (Criteria) this;
        }

        public Criteria andLocationProvinceBetween(String value1, String value2) {
            addCriterion("location_province between", value1, value2, "locationProvince");
            return (Criteria) this;
        }

        public Criteria andLocationProvinceNotBetween(String value1, String value2) {
            addCriterion("location_province not between", value1, value2, "locationProvince");
            return (Criteria) this;
        }

        public Criteria andLocationCityIsNull() {
            addCriterion("location_city is null");
            return (Criteria) this;
        }

        public Criteria andLocationCityIsNotNull() {
            addCriterion("location_city is not null");
            return (Criteria) this;
        }

        public Criteria andLocationCityEqualTo(String value) {
            addCriterion("location_city =", value, "locationCity");
            return (Criteria) this;
        }

        public Criteria andLocationCityNotEqualTo(String value) {
            addCriterion("location_city <>", value, "locationCity");
            return (Criteria) this;
        }

        public Criteria andLocationCityGreaterThan(String value) {
            addCriterion("location_city >", value, "locationCity");
            return (Criteria) this;
        }

        public Criteria andLocationCityGreaterThanOrEqualTo(String value) {
            addCriterion("location_city >=", value, "locationCity");
            return (Criteria) this;
        }

        public Criteria andLocationCityLessThan(String value) {
            addCriterion("location_city <", value, "locationCity");
            return (Criteria) this;
        }

        public Criteria andLocationCityLessThanOrEqualTo(String value) {
            addCriterion("location_city <=", value, "locationCity");
            return (Criteria) this;
        }

        public Criteria andLocationCityLike(String value) {
            addCriterion("location_city like", value, "locationCity");
            return (Criteria) this;
        }

        public Criteria andLocationCityNotLike(String value) {
            addCriterion("location_city not like", value, "locationCity");
            return (Criteria) this;
        }

        public Criteria andLocationCityIn(List<String> values) {
            addCriterion("location_city in", values, "locationCity");
            return (Criteria) this;
        }

        public Criteria andLocationCityNotIn(List<String> values) {
            addCriterion("location_city not in", values, "locationCity");
            return (Criteria) this;
        }

        public Criteria andLocationCityBetween(String value1, String value2) {
            addCriterion("location_city between", value1, value2, "locationCity");
            return (Criteria) this;
        }

        public Criteria andLocationCityNotBetween(String value1, String value2) {
            addCriterion("location_city not between", value1, value2, "locationCity");
            return (Criteria) this;
        }

        public Criteria andLocationAreaIsNull() {
            addCriterion("location_area is null");
            return (Criteria) this;
        }

        public Criteria andLocationAreaIsNotNull() {
            addCriterion("location_area is not null");
            return (Criteria) this;
        }

        public Criteria andLocationAreaEqualTo(String value) {
            addCriterion("location_area =", value, "locationArea");
            return (Criteria) this;
        }

        public Criteria andLocationAreaNotEqualTo(String value) {
            addCriterion("location_area <>", value, "locationArea");
            return (Criteria) this;
        }

        public Criteria andLocationAreaGreaterThan(String value) {
            addCriterion("location_area >", value, "locationArea");
            return (Criteria) this;
        }

        public Criteria andLocationAreaGreaterThanOrEqualTo(String value) {
            addCriterion("location_area >=", value, "locationArea");
            return (Criteria) this;
        }

        public Criteria andLocationAreaLessThan(String value) {
            addCriterion("location_area <", value, "locationArea");
            return (Criteria) this;
        }

        public Criteria andLocationAreaLessThanOrEqualTo(String value) {
            addCriterion("location_area <=", value, "locationArea");
            return (Criteria) this;
        }

        public Criteria andLocationAreaLike(String value) {
            addCriterion("location_area like", value, "locationArea");
            return (Criteria) this;
        }

        public Criteria andLocationAreaNotLike(String value) {
            addCriterion("location_area not like", value, "locationArea");
            return (Criteria) this;
        }

        public Criteria andLocationAreaIn(List<String> values) {
            addCriterion("location_area in", values, "locationArea");
            return (Criteria) this;
        }

        public Criteria andLocationAreaNotIn(List<String> values) {
            addCriterion("location_area not in", values, "locationArea");
            return (Criteria) this;
        }

        public Criteria andLocationAreaBetween(String value1, String value2) {
            addCriterion("location_area between", value1, value2, "locationArea");
            return (Criteria) this;
        }

        public Criteria andLocationAreaNotBetween(String value1, String value2) {
            addCriterion("location_area not between", value1, value2, "locationArea");
            return (Criteria) this;
        }

        public Criteria andLocationAddressIsNull() {
            addCriterion("location_address is null");
            return (Criteria) this;
        }

        public Criteria andLocationAddressIsNotNull() {
            addCriterion("location_address is not null");
            return (Criteria) this;
        }

        public Criteria andLocationAddressEqualTo(String value) {
            addCriterion("location_address =", value, "locationAddress");
            return (Criteria) this;
        }

        public Criteria andLocationAddressNotEqualTo(String value) {
            addCriterion("location_address <>", value, "locationAddress");
            return (Criteria) this;
        }

        public Criteria andLocationAddressGreaterThan(String value) {
            addCriterion("location_address >", value, "locationAddress");
            return (Criteria) this;
        }

        public Criteria andLocationAddressGreaterThanOrEqualTo(String value) {
            addCriterion("location_address >=", value, "locationAddress");
            return (Criteria) this;
        }

        public Criteria andLocationAddressLessThan(String value) {
            addCriterion("location_address <", value, "locationAddress");
            return (Criteria) this;
        }

        public Criteria andLocationAddressLessThanOrEqualTo(String value) {
            addCriterion("location_address <=", value, "locationAddress");
            return (Criteria) this;
        }

        public Criteria andLocationAddressLike(String value) {
            addCriterion("location_address like", value, "locationAddress");
            return (Criteria) this;
        }

        public Criteria andLocationAddressNotLike(String value) {
            addCriterion("location_address not like", value, "locationAddress");
            return (Criteria) this;
        }

        public Criteria andLocationAddressIn(List<String> values) {
            addCriterion("location_address in", values, "locationAddress");
            return (Criteria) this;
        }

        public Criteria andLocationAddressNotIn(List<String> values) {
            addCriterion("location_address not in", values, "locationAddress");
            return (Criteria) this;
        }

        public Criteria andLocationAddressBetween(String value1, String value2) {
            addCriterion("location_address between", value1, value2, "locationAddress");
            return (Criteria) this;
        }

        public Criteria andLocationAddressNotBetween(String value1, String value2) {
            addCriterion("location_address not between", value1, value2, "locationAddress");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceIsNull() {
            addCriterion("register_province is null");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceIsNotNull() {
            addCriterion("register_province is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceEqualTo(String value) {
            addCriterion("register_province =", value, "registerProvince");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceNotEqualTo(String value) {
            addCriterion("register_province <>", value, "registerProvince");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceGreaterThan(String value) {
            addCriterion("register_province >", value, "registerProvince");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("register_province >=", value, "registerProvince");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceLessThan(String value) {
            addCriterion("register_province <", value, "registerProvince");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceLessThanOrEqualTo(String value) {
            addCriterion("register_province <=", value, "registerProvince");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceLike(String value) {
            addCriterion("register_province like", value, "registerProvince");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceNotLike(String value) {
            addCriterion("register_province not like", value, "registerProvince");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceIn(List<String> values) {
            addCriterion("register_province in", values, "registerProvince");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceNotIn(List<String> values) {
            addCriterion("register_province not in", values, "registerProvince");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceBetween(String value1, String value2) {
            addCriterion("register_province between", value1, value2, "registerProvince");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceNotBetween(String value1, String value2) {
            addCriterion("register_province not between", value1, value2, "registerProvince");
            return (Criteria) this;
        }

        public Criteria andRegisterCityIsNull() {
            addCriterion("register_city is null");
            return (Criteria) this;
        }

        public Criteria andRegisterCityIsNotNull() {
            addCriterion("register_city is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterCityEqualTo(String value) {
            addCriterion("register_city =", value, "registerCity");
            return (Criteria) this;
        }

        public Criteria andRegisterCityNotEqualTo(String value) {
            addCriterion("register_city <>", value, "registerCity");
            return (Criteria) this;
        }

        public Criteria andRegisterCityGreaterThan(String value) {
            addCriterion("register_city >", value, "registerCity");
            return (Criteria) this;
        }

        public Criteria andRegisterCityGreaterThanOrEqualTo(String value) {
            addCriterion("register_city >=", value, "registerCity");
            return (Criteria) this;
        }

        public Criteria andRegisterCityLessThan(String value) {
            addCriterion("register_city <", value, "registerCity");
            return (Criteria) this;
        }

        public Criteria andRegisterCityLessThanOrEqualTo(String value) {
            addCriterion("register_city <=", value, "registerCity");
            return (Criteria) this;
        }

        public Criteria andRegisterCityLike(String value) {
            addCriterion("register_city like", value, "registerCity");
            return (Criteria) this;
        }

        public Criteria andRegisterCityNotLike(String value) {
            addCriterion("register_city not like", value, "registerCity");
            return (Criteria) this;
        }

        public Criteria andRegisterCityIn(List<String> values) {
            addCriterion("register_city in", values, "registerCity");
            return (Criteria) this;
        }

        public Criteria andRegisterCityNotIn(List<String> values) {
            addCriterion("register_city not in", values, "registerCity");
            return (Criteria) this;
        }

        public Criteria andRegisterCityBetween(String value1, String value2) {
            addCriterion("register_city between", value1, value2, "registerCity");
            return (Criteria) this;
        }

        public Criteria andRegisterCityNotBetween(String value1, String value2) {
            addCriterion("register_city not between", value1, value2, "registerCity");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaIsNull() {
            addCriterion("register_area is null");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaIsNotNull() {
            addCriterion("register_area is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaEqualTo(String value) {
            addCriterion("register_area =", value, "registerArea");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaNotEqualTo(String value) {
            addCriterion("register_area <>", value, "registerArea");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaGreaterThan(String value) {
            addCriterion("register_area >", value, "registerArea");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaGreaterThanOrEqualTo(String value) {
            addCriterion("register_area >=", value, "registerArea");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaLessThan(String value) {
            addCriterion("register_area <", value, "registerArea");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaLessThanOrEqualTo(String value) {
            addCriterion("register_area <=", value, "registerArea");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaLike(String value) {
            addCriterion("register_area like", value, "registerArea");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaNotLike(String value) {
            addCriterion("register_area not like", value, "registerArea");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaIn(List<String> values) {
            addCriterion("register_area in", values, "registerArea");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaNotIn(List<String> values) {
            addCriterion("register_area not in", values, "registerArea");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaBetween(String value1, String value2) {
            addCriterion("register_area between", value1, value2, "registerArea");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaNotBetween(String value1, String value2) {
            addCriterion("register_area not between", value1, value2, "registerArea");
            return (Criteria) this;
        }

        public Criteria andRegisterAddressIsNull() {
            addCriterion("register_address is null");
            return (Criteria) this;
        }

        public Criteria andRegisterAddressIsNotNull() {
            addCriterion("register_address is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterAddressEqualTo(String value) {
            addCriterion("register_address =", value, "registerAddress");
            return (Criteria) this;
        }

        public Criteria andRegisterAddressNotEqualTo(String value) {
            addCriterion("register_address <>", value, "registerAddress");
            return (Criteria) this;
        }

        public Criteria andRegisterAddressGreaterThan(String value) {
            addCriterion("register_address >", value, "registerAddress");
            return (Criteria) this;
        }

        public Criteria andRegisterAddressGreaterThanOrEqualTo(String value) {
            addCriterion("register_address >=", value, "registerAddress");
            return (Criteria) this;
        }

        public Criteria andRegisterAddressLessThan(String value) {
            addCriterion("register_address <", value, "registerAddress");
            return (Criteria) this;
        }

        public Criteria andRegisterAddressLessThanOrEqualTo(String value) {
            addCriterion("register_address <=", value, "registerAddress");
            return (Criteria) this;
        }

        public Criteria andRegisterAddressLike(String value) {
            addCriterion("register_address like", value, "registerAddress");
            return (Criteria) this;
        }

        public Criteria andRegisterAddressNotLike(String value) {
            addCriterion("register_address not like", value, "registerAddress");
            return (Criteria) this;
        }

        public Criteria andRegisterAddressIn(List<String> values) {
            addCriterion("register_address in", values, "registerAddress");
            return (Criteria) this;
        }

        public Criteria andRegisterAddressNotIn(List<String> values) {
            addCriterion("register_address not in", values, "registerAddress");
            return (Criteria) this;
        }

        public Criteria andRegisterAddressBetween(String value1, String value2) {
            addCriterion("register_address between", value1, value2, "registerAddress");
            return (Criteria) this;
        }

        public Criteria andRegisterAddressNotBetween(String value1, String value2) {
            addCriterion("register_address not between", value1, value2, "registerAddress");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeIsNull() {
            addCriterion("uniform_credit_code is null");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeIsNotNull() {
            addCriterion("uniform_credit_code is not null");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeEqualTo(String value) {
            addCriterion("uniform_credit_code =", value, "uniformCreditCode");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeNotEqualTo(String value) {
            addCriterion("uniform_credit_code <>", value, "uniformCreditCode");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeGreaterThan(String value) {
            addCriterion("uniform_credit_code >", value, "uniformCreditCode");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeGreaterThanOrEqualTo(String value) {
            addCriterion("uniform_credit_code >=", value, "uniformCreditCode");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeLessThan(String value) {
            addCriterion("uniform_credit_code <", value, "uniformCreditCode");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeLessThanOrEqualTo(String value) {
            addCriterion("uniform_credit_code <=", value, "uniformCreditCode");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeLike(String value) {
            addCriterion("uniform_credit_code like", value, "uniformCreditCode");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeNotLike(String value) {
            addCriterion("uniform_credit_code not like", value, "uniformCreditCode");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeIn(List<String> values) {
            addCriterion("uniform_credit_code in", values, "uniformCreditCode");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeNotIn(List<String> values) {
            addCriterion("uniform_credit_code not in", values, "uniformCreditCode");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeBetween(String value1, String value2) {
            addCriterion("uniform_credit_code between", value1, value2, "uniformCreditCode");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeNotBetween(String value1, String value2) {
            addCriterion("uniform_credit_code not between", value1, value2, "uniformCreditCode");
            return (Criteria) this;
        }

        public Criteria andLegalPersonIsNull() {
            addCriterion("legal_person is null");
            return (Criteria) this;
        }

        public Criteria andLegalPersonIsNotNull() {
            addCriterion("legal_person is not null");
            return (Criteria) this;
        }

        public Criteria andLegalPersonEqualTo(String value) {
            addCriterion("legal_person =", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonNotEqualTo(String value) {
            addCriterion("legal_person <>", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonGreaterThan(String value) {
            addCriterion("legal_person >", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonGreaterThanOrEqualTo(String value) {
            addCriterion("legal_person >=", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonLessThan(String value) {
            addCriterion("legal_person <", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonLessThanOrEqualTo(String value) {
            addCriterion("legal_person <=", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonLike(String value) {
            addCriterion("legal_person like", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonNotLike(String value) {
            addCriterion("legal_person not like", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonIn(List<String> values) {
            addCriterion("legal_person in", values, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonNotIn(List<String> values) {
            addCriterion("legal_person not in", values, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonBetween(String value1, String value2) {
            addCriterion("legal_person between", value1, value2, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonNotBetween(String value1, String value2) {
            addCriterion("legal_person not between", value1, value2, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andCellphoneIsNull() {
            addCriterion("cellphone is null");
            return (Criteria) this;
        }

        public Criteria andCellphoneIsNotNull() {
            addCriterion("cellphone is not null");
            return (Criteria) this;
        }

        public Criteria andCellphoneEqualTo(String value) {
            addCriterion("cellphone =", value, "cellphone");
            return (Criteria) this;
        }

        public Criteria andCellphoneNotEqualTo(String value) {
            addCriterion("cellphone <>", value, "cellphone");
            return (Criteria) this;
        }

        public Criteria andCellphoneGreaterThan(String value) {
            addCriterion("cellphone >", value, "cellphone");
            return (Criteria) this;
        }

        public Criteria andCellphoneGreaterThanOrEqualTo(String value) {
            addCriterion("cellphone >=", value, "cellphone");
            return (Criteria) this;
        }

        public Criteria andCellphoneLessThan(String value) {
            addCriterion("cellphone <", value, "cellphone");
            return (Criteria) this;
        }

        public Criteria andCellphoneLessThanOrEqualTo(String value) {
            addCriterion("cellphone <=", value, "cellphone");
            return (Criteria) this;
        }

        public Criteria andCellphoneLike(String value) {
            addCriterion("cellphone like", value, "cellphone");
            return (Criteria) this;
        }

        public Criteria andCellphoneNotLike(String value) {
            addCriterion("cellphone not like", value, "cellphone");
            return (Criteria) this;
        }

        public Criteria andCellphoneIn(List<String> values) {
            addCriterion("cellphone in", values, "cellphone");
            return (Criteria) this;
        }

        public Criteria andCellphoneNotIn(List<String> values) {
            addCriterion("cellphone not in", values, "cellphone");
            return (Criteria) this;
        }

        public Criteria andCellphoneBetween(String value1, String value2) {
            addCriterion("cellphone between", value1, value2, "cellphone");
            return (Criteria) this;
        }

        public Criteria andCellphoneNotBetween(String value1, String value2) {
            addCriterion("cellphone not between", value1, value2, "cellphone");
            return (Criteria) this;
        }

        public Criteria andIdNumberIsNull() {
            addCriterion("id_number is null");
            return (Criteria) this;
        }

        public Criteria andIdNumberIsNotNull() {
            addCriterion("id_number is not null");
            return (Criteria) this;
        }

        public Criteria andIdNumberEqualTo(String value) {
            addCriterion("id_number =", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotEqualTo(String value) {
            addCriterion("id_number <>", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberGreaterThan(String value) {
            addCriterion("id_number >", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberGreaterThanOrEqualTo(String value) {
            addCriterion("id_number >=", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLessThan(String value) {
            addCriterion("id_number <", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLessThanOrEqualTo(String value) {
            addCriterion("id_number <=", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLike(String value) {
            addCriterion("id_number like", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotLike(String value) {
            addCriterion("id_number not like", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberIn(List<String> values) {
            addCriterion("id_number in", values, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotIn(List<String> values) {
            addCriterion("id_number not in", values, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberBetween(String value1, String value2) {
            addCriterion("id_number between", value1, value2, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotBetween(String value1, String value2) {
            addCriterion("id_number not between", value1, value2, "idNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessLicensePicIsNull() {
            addCriterion("business_license_pic is null");
            return (Criteria) this;
        }

        public Criteria andBusinessLicensePicIsNotNull() {
            addCriterion("business_license_pic is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessLicensePicEqualTo(String value) {
            addCriterion("business_license_pic =", value, "businessLicensePic");
            return (Criteria) this;
        }

        public Criteria andBusinessLicensePicNotEqualTo(String value) {
            addCriterion("business_license_pic <>", value, "businessLicensePic");
            return (Criteria) this;
        }

        public Criteria andBusinessLicensePicGreaterThan(String value) {
            addCriterion("business_license_pic >", value, "businessLicensePic");
            return (Criteria) this;
        }

        public Criteria andBusinessLicensePicGreaterThanOrEqualTo(String value) {
            addCriterion("business_license_pic >=", value, "businessLicensePic");
            return (Criteria) this;
        }

        public Criteria andBusinessLicensePicLessThan(String value) {
            addCriterion("business_license_pic <", value, "businessLicensePic");
            return (Criteria) this;
        }

        public Criteria andBusinessLicensePicLessThanOrEqualTo(String value) {
            addCriterion("business_license_pic <=", value, "businessLicensePic");
            return (Criteria) this;
        }

        public Criteria andBusinessLicensePicLike(String value) {
            addCriterion("business_license_pic like", value, "businessLicensePic");
            return (Criteria) this;
        }

        public Criteria andBusinessLicensePicNotLike(String value) {
            addCriterion("business_license_pic not like", value, "businessLicensePic");
            return (Criteria) this;
        }

        public Criteria andBusinessLicensePicIn(List<String> values) {
            addCriterion("business_license_pic in", values, "businessLicensePic");
            return (Criteria) this;
        }

        public Criteria andBusinessLicensePicNotIn(List<String> values) {
            addCriterion("business_license_pic not in", values, "businessLicensePic");
            return (Criteria) this;
        }

        public Criteria andBusinessLicensePicBetween(String value1, String value2) {
            addCriterion("business_license_pic between", value1, value2, "businessLicensePic");
            return (Criteria) this;
        }

        public Criteria andBusinessLicensePicNotBetween(String value1, String value2) {
            addCriterion("business_license_pic not between", value1, value2, "businessLicensePic");
            return (Criteria) this;
        }

        public Criteria andCorpConsitutionDocIsNull() {
            addCriterion("corp_consitution_doc is null");
            return (Criteria) this;
        }

        public Criteria andCorpConsitutionDocIsNotNull() {
            addCriterion("corp_consitution_doc is not null");
            return (Criteria) this;
        }

        public Criteria andCorpConsitutionDocEqualTo(String value) {
            addCriterion("corp_consitution_doc =", value, "corpConsitutionDoc");
            return (Criteria) this;
        }

        public Criteria andCorpConsitutionDocNotEqualTo(String value) {
            addCriterion("corp_consitution_doc <>", value, "corpConsitutionDoc");
            return (Criteria) this;
        }

        public Criteria andCorpConsitutionDocGreaterThan(String value) {
            addCriterion("corp_consitution_doc >", value, "corpConsitutionDoc");
            return (Criteria) this;
        }

        public Criteria andCorpConsitutionDocGreaterThanOrEqualTo(String value) {
            addCriterion("corp_consitution_doc >=", value, "corpConsitutionDoc");
            return (Criteria) this;
        }

        public Criteria andCorpConsitutionDocLessThan(String value) {
            addCriterion("corp_consitution_doc <", value, "corpConsitutionDoc");
            return (Criteria) this;
        }

        public Criteria andCorpConsitutionDocLessThanOrEqualTo(String value) {
            addCriterion("corp_consitution_doc <=", value, "corpConsitutionDoc");
            return (Criteria) this;
        }

        public Criteria andCorpConsitutionDocLike(String value) {
            addCriterion("corp_consitution_doc like", value, "corpConsitutionDoc");
            return (Criteria) this;
        }

        public Criteria andCorpConsitutionDocNotLike(String value) {
            addCriterion("corp_consitution_doc not like", value, "corpConsitutionDoc");
            return (Criteria) this;
        }

        public Criteria andCorpConsitutionDocIn(List<String> values) {
            addCriterion("corp_consitution_doc in", values, "corpConsitutionDoc");
            return (Criteria) this;
        }

        public Criteria andCorpConsitutionDocNotIn(List<String> values) {
            addCriterion("corp_consitution_doc not in", values, "corpConsitutionDoc");
            return (Criteria) this;
        }

        public Criteria andCorpConsitutionDocBetween(String value1, String value2) {
            addCriterion("corp_consitution_doc between", value1, value2, "corpConsitutionDoc");
            return (Criteria) this;
        }

        public Criteria andCorpConsitutionDocNotBetween(String value1, String value2) {
            addCriterion("corp_consitution_doc not between", value1, value2, "corpConsitutionDoc");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("note is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("note is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("note =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("note <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("note >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("note >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("note <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("note <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("note like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("note not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("note in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("note not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("note between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("note not between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterionForJDBCDate("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterionForJDBCDate("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table supplier_info
     *
     * @mbg.generated do_not_delete_during_merge Sun Oct 14 03:46:43 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table supplier_info
     *
     * @mbg.generated Sun Oct 14 03:46:43 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}