package com.ut.scf.pojo.auto;

import java.util.ArrayList;
import java.util.List;

public class TfProjectAndCorpExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:41 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:41 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:41 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:41 CST 2017
	 */
	public TfProjectAndCorpExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:41 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:41 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:41 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:41 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:41 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:41 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:41 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:41 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:41 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:42 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:42 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andProjectIdIsNull() {
			addCriterion("project_id is null");
			return (Criteria) this;
		}

		public Criteria andProjectIdIsNotNull() {
			addCriterion("project_id is not null");
			return (Criteria) this;
		}

		public Criteria andProjectIdEqualTo(String value) {
			addCriterion("project_id =", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdNotEqualTo(String value) {
			addCriterion("project_id <>", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdGreaterThan(String value) {
			addCriterion("project_id >", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdGreaterThanOrEqualTo(String value) {
			addCriterion("project_id >=", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdLessThan(String value) {
			addCriterion("project_id <", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdLessThanOrEqualTo(String value) {
			addCriterion("project_id <=", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdLike(String value) {
			addCriterion("project_id like", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdNotLike(String value) {
			addCriterion("project_id not like", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdIn(List<String> values) {
			addCriterion("project_id in", values, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdNotIn(List<String> values) {
			addCriterion("project_id not in", values, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdBetween(String value1, String value2) {
			addCriterion("project_id between", value1, value2, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdNotBetween(String value1, String value2) {
			addCriterion("project_id not between", value1, value2, "projectId");
			return (Criteria) this;
		}

		public Criteria andCorpBuyIdIsNull() {
			addCriterion("corp_buy_id is null");
			return (Criteria) this;
		}

		public Criteria andCorpBuyIdIsNotNull() {
			addCriterion("corp_buy_id is not null");
			return (Criteria) this;
		}

		public Criteria andCorpBuyIdEqualTo(String value) {
			addCriterion("corp_buy_id =", value, "corpBuyId");
			return (Criteria) this;
		}

		public Criteria andCorpBuyIdNotEqualTo(String value) {
			addCriterion("corp_buy_id <>", value, "corpBuyId");
			return (Criteria) this;
		}

		public Criteria andCorpBuyIdGreaterThan(String value) {
			addCriterion("corp_buy_id >", value, "corpBuyId");
			return (Criteria) this;
		}

		public Criteria andCorpBuyIdGreaterThanOrEqualTo(String value) {
			addCriterion("corp_buy_id >=", value, "corpBuyId");
			return (Criteria) this;
		}

		public Criteria andCorpBuyIdLessThan(String value) {
			addCriterion("corp_buy_id <", value, "corpBuyId");
			return (Criteria) this;
		}

		public Criteria andCorpBuyIdLessThanOrEqualTo(String value) {
			addCriterion("corp_buy_id <=", value, "corpBuyId");
			return (Criteria) this;
		}

		public Criteria andCorpBuyIdLike(String value) {
			addCriterion("corp_buy_id like", value, "corpBuyId");
			return (Criteria) this;
		}

		public Criteria andCorpBuyIdNotLike(String value) {
			addCriterion("corp_buy_id not like", value, "corpBuyId");
			return (Criteria) this;
		}

		public Criteria andCorpBuyIdIn(List<String> values) {
			addCriterion("corp_buy_id in", values, "corpBuyId");
			return (Criteria) this;
		}

		public Criteria andCorpBuyIdNotIn(List<String> values) {
			addCriterion("corp_buy_id not in", values, "corpBuyId");
			return (Criteria) this;
		}

		public Criteria andCorpBuyIdBetween(String value1, String value2) {
			addCriterion("corp_buy_id between", value1, value2, "corpBuyId");
			return (Criteria) this;
		}

		public Criteria andCorpBuyIdNotBetween(String value1, String value2) {
			addCriterion("corp_buy_id not between", value1, value2, "corpBuyId");
			return (Criteria) this;
		}

		public Criteria andCorpSaleIdIsNull() {
			addCriterion("corp_sale_id is null");
			return (Criteria) this;
		}

		public Criteria andCorpSaleIdIsNotNull() {
			addCriterion("corp_sale_id is not null");
			return (Criteria) this;
		}

		public Criteria andCorpSaleIdEqualTo(String value) {
			addCriterion("corp_sale_id =", value, "corpSaleId");
			return (Criteria) this;
		}

		public Criteria andCorpSaleIdNotEqualTo(String value) {
			addCriterion("corp_sale_id <>", value, "corpSaleId");
			return (Criteria) this;
		}

		public Criteria andCorpSaleIdGreaterThan(String value) {
			addCriterion("corp_sale_id >", value, "corpSaleId");
			return (Criteria) this;
		}

		public Criteria andCorpSaleIdGreaterThanOrEqualTo(String value) {
			addCriterion("corp_sale_id >=", value, "corpSaleId");
			return (Criteria) this;
		}

		public Criteria andCorpSaleIdLessThan(String value) {
			addCriterion("corp_sale_id <", value, "corpSaleId");
			return (Criteria) this;
		}

		public Criteria andCorpSaleIdLessThanOrEqualTo(String value) {
			addCriterion("corp_sale_id <=", value, "corpSaleId");
			return (Criteria) this;
		}

		public Criteria andCorpSaleIdLike(String value) {
			addCriterion("corp_sale_id like", value, "corpSaleId");
			return (Criteria) this;
		}

		public Criteria andCorpSaleIdNotLike(String value) {
			addCriterion("corp_sale_id not like", value, "corpSaleId");
			return (Criteria) this;
		}

		public Criteria andCorpSaleIdIn(List<String> values) {
			addCriterion("corp_sale_id in", values, "corpSaleId");
			return (Criteria) this;
		}

		public Criteria andCorpSaleIdNotIn(List<String> values) {
			addCriterion("corp_sale_id not in", values, "corpSaleId");
			return (Criteria) this;
		}

		public Criteria andCorpSaleIdBetween(String value1, String value2) {
			addCriterion("corp_sale_id between", value1, value2, "corpSaleId");
			return (Criteria) this;
		}

		public Criteria andCorpSaleIdNotBetween(String value1, String value2) {
			addCriterion("corp_sale_id not between", value1, value2, "corpSaleId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:42 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tf_project_and_corp
     *
     * @mbg.generated do_not_delete_during_merge Tue Oct 24 15:08:25 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}