package com.ut.scf.pojo.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.math.BigDecimal;

public class TfRateInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tf_rate_info.rate_id
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	private String rateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tf_rate_info.interest_rate
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	private BigDecimal interestRate;
	public void setInterestRate(BigDecimal interestRate) {
		this.interestRate = interestRate;
	}

	public void setManageFeeRate(BigDecimal manageFeeRate) {
		this.manageFeeRate = manageFeeRate;
	}

	public void setManageFeeAmount(BigDecimal manageFeeAmount) {
		this.manageFeeAmount = manageFeeAmount;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tf_rate_info.receipt_way
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	private String receiptWay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tf_rate_info.manage_fee_rate
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	private BigDecimal manageFeeRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tf_rate_info.manage_fee_amount
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	private BigDecimal manageFeeAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tf_rate_info.mng_fee_pay_way
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	private String mngFeePayWay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tf_rate_info.create_time
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tf_rate_info.rate_id
	 * @return  the value of tf_rate_info.rate_id
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	public String getRateId() {
		return rateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tf_rate_info.rate_id
	 * @param rateId  the value for tf_rate_info.rate_id
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	public void setRateId(String rateId) {
		this.rateId = rateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tf_rate_info.interest_rate
	 * @return  the value of tf_rate_info.interest_rate
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	public BigDecimal getInterestRate() {
		return interestRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tf_rate_info.interest_rate
	 * @param bigDecimal  the value for tf_rate_info.interest_rate
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tf_rate_info.receipt_way
	 * @return  the value of tf_rate_info.receipt_way
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	public String getReceiptWay() {
		return receiptWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tf_rate_info.receipt_way
	 * @param receiptWay  the value for tf_rate_info.receipt_way
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	public void setReceiptWay(String receiptWay) {
		this.receiptWay = receiptWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tf_rate_info.manage_fee_rate
	 * @return  the value of tf_rate_info.manage_fee_rate
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	public BigDecimal getManageFeeRate() {
		return manageFeeRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tf_rate_info.manage_fee_rate
	 * @param bigDecimal  the value for tf_rate_info.manage_fee_rate
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tf_rate_info.manage_fee_amount
	 * @return  the value of tf_rate_info.manage_fee_amount
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	public BigDecimal getManageFeeAmount() {
		return manageFeeAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tf_rate_info.manage_fee_amount
	 * @param bigDecimal  the value for tf_rate_info.manage_fee_amount
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tf_rate_info.mng_fee_pay_way
	 * @return  the value of tf_rate_info.mng_fee_pay_way
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	public String getMngFeePayWay() {
		return mngFeePayWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tf_rate_info.mng_fee_pay_way
	 * @param mngFeePayWay  the value for tf_rate_info.mng_fee_pay_way
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	public void setMngFeePayWay(String mngFeePayWay) {
		this.mngFeePayWay = mngFeePayWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tf_rate_info.create_time
	 * @return  the value of tf_rate_info.create_time
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tf_rate_info.create_time
	 * @param createTime  the value for tf_rate_info.create_time
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}