package com.ut.scf.dao.auto;

import com.ut.scf.pojo.auto.RepaymentPlanUserInfo;
import com.ut.scf.pojo.auto.RepaymentPlanUserUnInfo;
import com.ut.scf.pojo.auto.RepaymentPlanUserUnInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RepaymentPlanUserUnInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    long countByExample(RepaymentPlanUserUnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    int deleteByExample(RepaymentPlanUserUnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    int insert(RepaymentPlanUserUnInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    int insertSelective(RepaymentPlanUserUnInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    List<RepaymentPlanUserUnInfo> selectByExample(RepaymentPlanUserUnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    RepaymentPlanUserUnInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") RepaymentPlanUserUnInfo record, @Param("example") RepaymentPlanUserUnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    int updateByExample(@Param("record") RepaymentPlanUserUnInfo record, @Param("example") RepaymentPlanUserUnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(RepaymentPlanUserUnInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_un_info
     *
     * @mbg.generated Mon Aug 20 17:58:43 GMT+08:00 2018
     */
    int updateByPrimaryKey(RepaymentPlanUserUnInfo record);
	int insertListRepayment(List<RepaymentPlanUserUnInfo> repaymentList);
}