package com.ut.scf.pojo.auto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.math.BigDecimal;

public class TfProjectInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tf_project_info
	 * @mbg.generated  Wed Nov 01 14:51:02 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tf_project_info
	 * @mbg.generated  Wed Nov 01 14:51:02 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tf_project_info
	 * @mbg.generated  Wed Nov 01 14:51:02 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_info
	 * @mbg.generated  Wed Nov 01 14:51:02 CST 2017
	 */
	public TfProjectInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_info
	 * @mbg.generated  Wed Nov 01 14:51:02 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_info
	 * @mbg.generated  Wed Nov 01 14:51:02 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_info
	 * @mbg.generated  Wed Nov 01 14:51:02 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_info
	 * @mbg.generated  Wed Nov 01 14:51:02 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_info
	 * @mbg.generated  Wed Nov 01 14:51:02 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_info
	 * @mbg.generated  Wed Nov 01 14:51:02 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_info
	 * @mbg.generated  Wed Nov 01 14:51:02 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_info
	 * @mbg.generated  Wed Nov 01 14:51:02 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_info
	 * @mbg.generated  Wed Nov 01 14:51:02 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_info
	 * @mbg.generated  Wed Nov 01 14:51:02 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tf_project_info
	 * @mbg.generated  Wed Nov 01 14:51:02 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andProjectIdIsNull() {
			addCriterion("project_id is null");
			return (Criteria) this;
		}

		public Criteria andProjectIdIsNotNull() {
			addCriterion("project_id is not null");
			return (Criteria) this;
		}

		public Criteria andProjectIdEqualTo(String value) {
			addCriterion("project_id =", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdNotEqualTo(String value) {
			addCriterion("project_id <>", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdGreaterThan(String value) {
			addCriterion("project_id >", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdGreaterThanOrEqualTo(String value) {
			addCriterion("project_id >=", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdLessThan(String value) {
			addCriterion("project_id <", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdLessThanOrEqualTo(String value) {
			addCriterion("project_id <=", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdLike(String value) {
			addCriterion("project_id like", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdNotLike(String value) {
			addCriterion("project_id not like", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdIn(List<String> values) {
			addCriterion("project_id in", values, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdNotIn(List<String> values) {
			addCriterion("project_id not in", values, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdBetween(String value1, String value2) {
			addCriterion("project_id between", value1, value2, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdNotBetween(String value1, String value2) {
			addCriterion("project_id not between", value1, value2, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectNameIsNull() {
			addCriterion("project_name is null");
			return (Criteria) this;
		}

		public Criteria andProjectNameIsNotNull() {
			addCriterion("project_name is not null");
			return (Criteria) this;
		}

		public Criteria andProjectNameEqualTo(String value) {
			addCriterion("project_name =", value, "projectName");
			return (Criteria) this;
		}

		public Criteria andProjectNameNotEqualTo(String value) {
			addCriterion("project_name <>", value, "projectName");
			return (Criteria) this;
		}

		public Criteria andProjectNameGreaterThan(String value) {
			addCriterion("project_name >", value, "projectName");
			return (Criteria) this;
		}

		public Criteria andProjectNameGreaterThanOrEqualTo(String value) {
			addCriterion("project_name >=", value, "projectName");
			return (Criteria) this;
		}

		public Criteria andProjectNameLessThan(String value) {
			addCriterion("project_name <", value, "projectName");
			return (Criteria) this;
		}

		public Criteria andProjectNameLessThanOrEqualTo(String value) {
			addCriterion("project_name <=", value, "projectName");
			return (Criteria) this;
		}

		public Criteria andProjectNameLike(String value) {
			addCriterion("project_name like", value, "projectName");
			return (Criteria) this;
		}

		public Criteria andProjectNameNotLike(String value) {
			addCriterion("project_name not like", value, "projectName");
			return (Criteria) this;
		}

		public Criteria andProjectNameIn(List<String> values) {
			addCriterion("project_name in", values, "projectName");
			return (Criteria) this;
		}

		public Criteria andProjectNameNotIn(List<String> values) {
			addCriterion("project_name not in", values, "projectName");
			return (Criteria) this;
		}

		public Criteria andProjectNameBetween(String value1, String value2) {
			addCriterion("project_name between", value1, value2, "projectName");
			return (Criteria) this;
		}

		public Criteria andProjectNameNotBetween(String value1, String value2) {
			addCriterion("project_name not between", value1, value2, "projectName");
			return (Criteria) this;
		}

		public Criteria andProjectStatusIsNull() {
			addCriterion("project_status is null");
			return (Criteria) this;
		}

		public Criteria andProjectStatusIsNotNull() {
			addCriterion("project_status is not null");
			return (Criteria) this;
		}

		public Criteria andProjectStatusEqualTo(String value) {
			addCriterion("project_status =", value, "projectStatus");
			return (Criteria) this;
		}

		public Criteria andProjectStatusNotEqualTo(String value) {
			addCriterion("project_status <>", value, "projectStatus");
			return (Criteria) this;
		}

		public Criteria andProjectStatusGreaterThan(String value) {
			addCriterion("project_status >", value, "projectStatus");
			return (Criteria) this;
		}

		public Criteria andProjectStatusGreaterThanOrEqualTo(String value) {
			addCriterion("project_status >=", value, "projectStatus");
			return (Criteria) this;
		}

		public Criteria andProjectStatusLessThan(String value) {
			addCriterion("project_status <", value, "projectStatus");
			return (Criteria) this;
		}

		public Criteria andProjectStatusLessThanOrEqualTo(String value) {
			addCriterion("project_status <=", value, "projectStatus");
			return (Criteria) this;
		}

		public Criteria andProjectStatusLike(String value) {
			addCriterion("project_status like", value, "projectStatus");
			return (Criteria) this;
		}

		public Criteria andProjectStatusNotLike(String value) {
			addCriterion("project_status not like", value, "projectStatus");
			return (Criteria) this;
		}

		public Criteria andProjectStatusIn(List<String> values) {
			addCriterion("project_status in", values, "projectStatus");
			return (Criteria) this;
		}

		public Criteria andProjectStatusNotIn(List<String> values) {
			addCriterion("project_status not in", values, "projectStatus");
			return (Criteria) this;
		}

		public Criteria andProjectStatusBetween(String value1, String value2) {
			addCriterion("project_status between", value1, value2, "projectStatus");
			return (Criteria) this;
		}

		public Criteria andProjectStatusNotBetween(String value1, String value2) {
			addCriterion("project_status not between", value1, value2, "projectStatus");
			return (Criteria) this;
		}

		public Criteria andFactoringTypeIsNull() {
			addCriterion("factoring_type is null");
			return (Criteria) this;
		}

		public Criteria andFactoringTypeIsNotNull() {
			addCriterion("factoring_type is not null");
			return (Criteria) this;
		}

		public Criteria andFactoringTypeEqualTo(String value) {
			addCriterion("factoring_type =", value, "factoringType");
			return (Criteria) this;
		}

		public Criteria andFactoringTypeNotEqualTo(String value) {
			addCriterion("factoring_type <>", value, "factoringType");
			return (Criteria) this;
		}

		public Criteria andFactoringTypeGreaterThan(String value) {
			addCriterion("factoring_type >", value, "factoringType");
			return (Criteria) this;
		}

		public Criteria andFactoringTypeGreaterThanOrEqualTo(String value) {
			addCriterion("factoring_type >=", value, "factoringType");
			return (Criteria) this;
		}

		public Criteria andFactoringTypeLessThan(String value) {
			addCriterion("factoring_type <", value, "factoringType");
			return (Criteria) this;
		}

		public Criteria andFactoringTypeLessThanOrEqualTo(String value) {
			addCriterion("factoring_type <=", value, "factoringType");
			return (Criteria) this;
		}

		public Criteria andFactoringTypeLike(String value) {
			addCriterion("factoring_type like", value, "factoringType");
			return (Criteria) this;
		}

		public Criteria andFactoringTypeNotLike(String value) {
			addCriterion("factoring_type not like", value, "factoringType");
			return (Criteria) this;
		}

		public Criteria andFactoringTypeIn(List<String> values) {
			addCriterion("factoring_type in", values, "factoringType");
			return (Criteria) this;
		}

		public Criteria andFactoringTypeNotIn(List<String> values) {
			addCriterion("factoring_type not in", values, "factoringType");
			return (Criteria) this;
		}

		public Criteria andFactoringTypeBetween(String value1, String value2) {
			addCriterion("factoring_type between", value1, value2, "factoringType");
			return (Criteria) this;
		}

		public Criteria andFactoringTypeNotBetween(String value1, String value2) {
			addCriterion("factoring_type not between", value1, value2, "factoringType");
			return (Criteria) this;
		}

		public Criteria andFinancingAmountIsNull() {
			addCriterion("financing_amount is null");
			return (Criteria) this;
		}

		public Criteria andFinancingAmountIsNotNull() {
			addCriterion("financing_amount is not null");
			return (Criteria) this;
		}

		public Criteria andFinancingAmountEqualTo(BigDecimal value) {
			addCriterion("financing_amount =", value, "financingAmount");
			return (Criteria) this;
		}

		public Criteria andFinancingAmountNotEqualTo(BigDecimal value) {
			addCriterion("financing_amount <>", value, "financingAmount");
			return (Criteria) this;
		}

		public Criteria andFinancingAmountGreaterThan(BigDecimal value) {
			addCriterion("financing_amount >", value, "financingAmount");
			return (Criteria) this;
		}

		public Criteria andFinancingAmountGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("financing_amount >=", value, "financingAmount");
			return (Criteria) this;
		}

		public Criteria andFinancingAmountLessThan(BigDecimal value) {
			addCriterion("financing_amount <", value, "financingAmount");
			return (Criteria) this;
		}

		public Criteria andFinancingAmountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("financing_amount <=", value, "financingAmount");
			return (Criteria) this;
		}

		public Criteria andFinancingAmountIn(List<BigDecimal> values) {
			addCriterion("financing_amount in", values, "financingAmount");
			return (Criteria) this;
		}

		public Criteria andFinancingAmountNotIn(List<BigDecimal> values) {
			addCriterion("financing_amount not in", values, "financingAmount");
			return (Criteria) this;
		}

		public Criteria andFinancingAmountBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("financing_amount between", value1, value2, "financingAmount");
			return (Criteria) this;
		}

		public Criteria andFinancingAmountNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("financing_amount not between", value1, value2, "financingAmount");
			return (Criteria) this;
		}

		public Criteria andFinancingTermIsNull() {
			addCriterion("financing_term is null");
			return (Criteria) this;
		}

		public Criteria andFinancingTermIsNotNull() {
			addCriterion("financing_term is not null");
			return (Criteria) this;
		}

		public Criteria andFinancingTermEqualTo(BigDecimal value) {
			addCriterion("financing_term =", value, "financingTerm");
			return (Criteria) this;
		}

		public Criteria andFinancingTermNotEqualTo(BigDecimal value) {
			addCriterion("financing_term <>", value, "financingTerm");
			return (Criteria) this;
		}

		public Criteria andFinancingTermGreaterThan(BigDecimal value) {
			addCriterion("financing_term >", value, "financingTerm");
			return (Criteria) this;
		}

		public Criteria andFinancingTermGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("financing_term >=", value, "financingTerm");
			return (Criteria) this;
		}

		public Criteria andFinancingTermLessThan(BigDecimal value) {
			addCriterion("financing_term <", value, "financingTerm");
			return (Criteria) this;
		}

		public Criteria andFinancingTermLessThanOrEqualTo(BigDecimal value) {
			addCriterion("financing_term <=", value, "financingTerm");
			return (Criteria) this;
		}

		public Criteria andFinancingTermIn(List<BigDecimal> values) {
			addCriterion("financing_term in", values, "financingTerm");
			return (Criteria) this;
		}

		public Criteria andFinancingTermNotIn(List<BigDecimal> values) {
			addCriterion("financing_term not in", values, "financingTerm");
			return (Criteria) this;
		}

		public Criteria andFinancingTermBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("financing_term between", value1, value2, "financingTerm");
			return (Criteria) this;
		}

		public Criteria andFinancingTermNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("financing_term not between", value1, value2, "financingTerm");
			return (Criteria) this;
		}

		public Criteria andRateIdIsNull() {
			addCriterion("rate_id is null");
			return (Criteria) this;
		}

		public Criteria andRateIdIsNotNull() {
			addCriterion("rate_id is not null");
			return (Criteria) this;
		}

		public Criteria andRateIdEqualTo(String value) {
			addCriterion("rate_id =", value, "rateId");
			return (Criteria) this;
		}

		public Criteria andRateIdNotEqualTo(String value) {
			addCriterion("rate_id <>", value, "rateId");
			return (Criteria) this;
		}

		public Criteria andRateIdGreaterThan(String value) {
			addCriterion("rate_id >", value, "rateId");
			return (Criteria) this;
		}

		public Criteria andRateIdGreaterThanOrEqualTo(String value) {
			addCriterion("rate_id >=", value, "rateId");
			return (Criteria) this;
		}

		public Criteria andRateIdLessThan(String value) {
			addCriterion("rate_id <", value, "rateId");
			return (Criteria) this;
		}

		public Criteria andRateIdLessThanOrEqualTo(String value) {
			addCriterion("rate_id <=", value, "rateId");
			return (Criteria) this;
		}

		public Criteria andRateIdLike(String value) {
			addCriterion("rate_id like", value, "rateId");
			return (Criteria) this;
		}

		public Criteria andRateIdNotLike(String value) {
			addCriterion("rate_id not like", value, "rateId");
			return (Criteria) this;
		}

		public Criteria andRateIdIn(List<String> values) {
			addCriterion("rate_id in", values, "rateId");
			return (Criteria) this;
		}

		public Criteria andRateIdNotIn(List<String> values) {
			addCriterion("rate_id not in", values, "rateId");
			return (Criteria) this;
		}

		public Criteria andRateIdBetween(String value1, String value2) {
			addCriterion("rate_id between", value1, value2, "rateId");
			return (Criteria) this;
		}

		public Criteria andRateIdNotBetween(String value1, String value2) {
			addCriterion("rate_id not between", value1, value2, "rateId");
			return (Criteria) this;
		}

		public Criteria andRepaymentWayIsNull() {
			addCriterion("repayment_way is null");
			return (Criteria) this;
		}

		public Criteria andRepaymentWayIsNotNull() {
			addCriterion("repayment_way is not null");
			return (Criteria) this;
		}

		public Criteria andRepaymentWayEqualTo(String value) {
			addCriterion("repayment_way =", value, "repaymentWay");
			return (Criteria) this;
		}

		public Criteria andRepaymentWayNotEqualTo(String value) {
			addCriterion("repayment_way <>", value, "repaymentWay");
			return (Criteria) this;
		}

		public Criteria andRepaymentWayGreaterThan(String value) {
			addCriterion("repayment_way >", value, "repaymentWay");
			return (Criteria) this;
		}

		public Criteria andRepaymentWayGreaterThanOrEqualTo(String value) {
			addCriterion("repayment_way >=", value, "repaymentWay");
			return (Criteria) this;
		}

		public Criteria andRepaymentWayLessThan(String value) {
			addCriterion("repayment_way <", value, "repaymentWay");
			return (Criteria) this;
		}

		public Criteria andRepaymentWayLessThanOrEqualTo(String value) {
			addCriterion("repayment_way <=", value, "repaymentWay");
			return (Criteria) this;
		}

		public Criteria andRepaymentWayLike(String value) {
			addCriterion("repayment_way like", value, "repaymentWay");
			return (Criteria) this;
		}

		public Criteria andRepaymentWayNotLike(String value) {
			addCriterion("repayment_way not like", value, "repaymentWay");
			return (Criteria) this;
		}

		public Criteria andRepaymentWayIn(List<String> values) {
			addCriterion("repayment_way in", values, "repaymentWay");
			return (Criteria) this;
		}

		public Criteria andRepaymentWayNotIn(List<String> values) {
			addCriterion("repayment_way not in", values, "repaymentWay");
			return (Criteria) this;
		}

		public Criteria andRepaymentWayBetween(String value1, String value2) {
			addCriterion("repayment_way between", value1, value2, "repaymentWay");
			return (Criteria) this;
		}

		public Criteria andRepaymentWayNotBetween(String value1, String value2) {
			addCriterion("repayment_way not between", value1, value2, "repaymentWay");
			return (Criteria) this;
		}

		public Criteria andReapymentAmountIsNull() {
			addCriterion("reapyment_amount is null");
			return (Criteria) this;
		}

		public Criteria andReapymentAmountIsNotNull() {
			addCriterion("reapyment_amount is not null");
			return (Criteria) this;
		}

		public Criteria andReapymentAmountEqualTo(BigDecimal value) {
			addCriterion("reapyment_amount =", value, "reapymentAmount");
			return (Criteria) this;
		}

		public Criteria andReapymentAmountNotEqualTo(BigDecimal value) {
			addCriterion("reapyment_amount <>", value, "reapymentAmount");
			return (Criteria) this;
		}

		public Criteria andReapymentAmountGreaterThan(BigDecimal value) {
			addCriterion("reapyment_amount >", value, "reapymentAmount");
			return (Criteria) this;
		}

		public Criteria andReapymentAmountGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("reapyment_amount >=", value, "reapymentAmount");
			return (Criteria) this;
		}

		public Criteria andReapymentAmountLessThan(BigDecimal value) {
			addCriterion("reapyment_amount <", value, "reapymentAmount");
			return (Criteria) this;
		}

		public Criteria andReapymentAmountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("reapyment_amount <=", value, "reapymentAmount");
			return (Criteria) this;
		}

		public Criteria andReapymentAmountIn(List<BigDecimal> values) {
			addCriterion("reapyment_amount in", values, "reapymentAmount");
			return (Criteria) this;
		}

		public Criteria andReapymentAmountNotIn(List<BigDecimal> values) {
			addCriterion("reapyment_amount not in", values, "reapymentAmount");
			return (Criteria) this;
		}

		public Criteria andReapymentAmountBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("reapyment_amount between", value1, value2, "reapymentAmount");
			return (Criteria) this;
		}

		public Criteria andReapymentAmountNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("reapyment_amount not between", value1, value2, "reapymentAmount");
			return (Criteria) this;
		}

		public Criteria andReturnRateIsNull() {
			addCriterion("return_rate is null");
			return (Criteria) this;
		}

		public Criteria andReturnRateIsNotNull() {
			addCriterion("return_rate is not null");
			return (Criteria) this;
		}

		public Criteria andReturnRateEqualTo(BigDecimal value) {
			addCriterion("return_rate =", value, "returnRate");
			return (Criteria) this;
		}

		public Criteria andReturnRateNotEqualTo(BigDecimal value) {
			addCriterion("return_rate <>", value, "returnRate");
			return (Criteria) this;
		}

		public Criteria andReturnRateGreaterThan(BigDecimal value) {
			addCriterion("return_rate >", value, "returnRate");
			return (Criteria) this;
		}

		public Criteria andReturnRateGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("return_rate >=", value, "returnRate");
			return (Criteria) this;
		}

		public Criteria andReturnRateLessThan(BigDecimal value) {
			addCriterion("return_rate <", value, "returnRate");
			return (Criteria) this;
		}

		public Criteria andReturnRateLessThanOrEqualTo(BigDecimal value) {
			addCriterion("return_rate <=", value, "returnRate");
			return (Criteria) this;
		}

		public Criteria andReturnRateIn(List<BigDecimal> values) {
			addCriterion("return_rate in", values, "returnRate");
			return (Criteria) this;
		}

		public Criteria andReturnRateNotIn(List<BigDecimal> values) {
			addCriterion("return_rate not in", values, "returnRate");
			return (Criteria) this;
		}

		public Criteria andReturnRateBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("return_rate between", value1, value2, "returnRate");
			return (Criteria) this;
		}

		public Criteria andReturnRateNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("return_rate not between", value1, value2, "returnRate");
			return (Criteria) this;
		}

		public Criteria andRiskMitigationMeasuresIsNull() {
			addCriterion("risk_mitigation_measures is null");
			return (Criteria) this;
		}

		public Criteria andRiskMitigationMeasuresIsNotNull() {
			addCriterion("risk_mitigation_measures is not null");
			return (Criteria) this;
		}

		public Criteria andRiskMitigationMeasuresEqualTo(String value) {
			addCriterion("risk_mitigation_measures =", value, "riskMitigationMeasures");
			return (Criteria) this;
		}

		public Criteria andRiskMitigationMeasuresNotEqualTo(String value) {
			addCriterion("risk_mitigation_measures <>", value, "riskMitigationMeasures");
			return (Criteria) this;
		}

		public Criteria andRiskMitigationMeasuresGreaterThan(String value) {
			addCriterion("risk_mitigation_measures >", value, "riskMitigationMeasures");
			return (Criteria) this;
		}

		public Criteria andRiskMitigationMeasuresGreaterThanOrEqualTo(String value) {
			addCriterion("risk_mitigation_measures >=", value, "riskMitigationMeasures");
			return (Criteria) this;
		}

		public Criteria andRiskMitigationMeasuresLessThan(String value) {
			addCriterion("risk_mitigation_measures <", value, "riskMitigationMeasures");
			return (Criteria) this;
		}

		public Criteria andRiskMitigationMeasuresLessThanOrEqualTo(String value) {
			addCriterion("risk_mitigation_measures <=", value, "riskMitigationMeasures");
			return (Criteria) this;
		}

		public Criteria andRiskMitigationMeasuresLike(String value) {
			addCriterion("risk_mitigation_measures like", value, "riskMitigationMeasures");
			return (Criteria) this;
		}

		public Criteria andRiskMitigationMeasuresNotLike(String value) {
			addCriterion("risk_mitigation_measures not like", value, "riskMitigationMeasures");
			return (Criteria) this;
		}

		public Criteria andRiskMitigationMeasuresIn(List<String> values) {
			addCriterion("risk_mitigation_measures in", values, "riskMitigationMeasures");
			return (Criteria) this;
		}

		public Criteria andRiskMitigationMeasuresNotIn(List<String> values) {
			addCriterion("risk_mitigation_measures not in", values, "riskMitigationMeasures");
			return (Criteria) this;
		}

		public Criteria andRiskMitigationMeasuresBetween(String value1, String value2) {
			addCriterion("risk_mitigation_measures between", value1, value2, "riskMitigationMeasures");
			return (Criteria) this;
		}

		public Criteria andRiskMitigationMeasuresNotBetween(String value1, String value2) {
			addCriterion("risk_mitigation_measures not between", value1, value2, "riskMitigationMeasures");
			return (Criteria) this;
		}

		public Criteria andProjectDescriptionIsNull() {
			addCriterion("project_description is null");
			return (Criteria) this;
		}

		public Criteria andProjectDescriptionIsNotNull() {
			addCriterion("project_description is not null");
			return (Criteria) this;
		}

		public Criteria andProjectDescriptionEqualTo(String value) {
			addCriterion("project_description =", value, "projectDescription");
			return (Criteria) this;
		}

		public Criteria andProjectDescriptionNotEqualTo(String value) {
			addCriterion("project_description <>", value, "projectDescription");
			return (Criteria) this;
		}

		public Criteria andProjectDescriptionGreaterThan(String value) {
			addCriterion("project_description >", value, "projectDescription");
			return (Criteria) this;
		}

		public Criteria andProjectDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("project_description >=", value, "projectDescription");
			return (Criteria) this;
		}

		public Criteria andProjectDescriptionLessThan(String value) {
			addCriterion("project_description <", value, "projectDescription");
			return (Criteria) this;
		}

		public Criteria andProjectDescriptionLessThanOrEqualTo(String value) {
			addCriterion("project_description <=", value, "projectDescription");
			return (Criteria) this;
		}

		public Criteria andProjectDescriptionLike(String value) {
			addCriterion("project_description like", value, "projectDescription");
			return (Criteria) this;
		}

		public Criteria andProjectDescriptionNotLike(String value) {
			addCriterion("project_description not like", value, "projectDescription");
			return (Criteria) this;
		}

		public Criteria andProjectDescriptionIn(List<String> values) {
			addCriterion("project_description in", values, "projectDescription");
			return (Criteria) this;
		}

		public Criteria andProjectDescriptionNotIn(List<String> values) {
			addCriterion("project_description not in", values, "projectDescription");
			return (Criteria) this;
		}

		public Criteria andProjectDescriptionBetween(String value1, String value2) {
			addCriterion("project_description between", value1, value2, "projectDescription");
			return (Criteria) this;
		}

		public Criteria andProjectDescriptionNotBetween(String value1, String value2) {
			addCriterion("project_description not between", value1, value2, "projectDescription");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tf_project_info
	 * @mbg.generated  Wed Nov 01 14:51:02 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tf_project_info
     *
     * @mbg.generated do_not_delete_during_merge Tue Oct 24 15:06:03 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}