package com.ut.scf.pojo.auto;

import java.math.BigDecimal;

public class WingPaymentStaticInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wing_payment_static_info.id
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wing_payment_static_info.people_type
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    private String peopleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wing_payment_static_info.order_date
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    private String orderDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wing_payment_static_info.report_month
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    private String reportMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wing_payment_static_info.order_sum_money
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    private BigDecimal orderSumMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wing_payment_static_info.order_sum_count
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    private BigDecimal orderSumCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wing_payment_static_info.has_not_pay_amt
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    private BigDecimal hasNotPayAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wing_payment_static_info.rest_count
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    private Integer restCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wing_payment_static_info.normal_loan_balance
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    private BigDecimal normalLoanBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wing_payment_static_info.m1_overdue_loans
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    private BigDecimal m1OverdueLoans;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wing_payment_static_info.m2_overdue_loans
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    private BigDecimal m2OverdueLoans;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wing_payment_static_info.m3_overdue_loans
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    private BigDecimal m3OverdueLoans;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wing_payment_static_info.m4_overdue_loans
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    private BigDecimal m4OverdueLoans;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wing_payment_static_info.m5_overdue_loans
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    private BigDecimal m5OverdueLoans;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wing_payment_static_info.m1_overdue_counts
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    private Integer m1OverdueCounts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wing_payment_static_info.m2_overdue_counts
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    private Integer m2OverdueCounts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wing_payment_static_info.m3_overdue_counts
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    private Integer m3OverdueCounts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wing_payment_static_info.m4_overdue_counts
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    private Integer m4OverdueCounts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wing_payment_static_info.m5_overdue_counts
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    private Integer m5OverdueCounts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wing_payment_static_info.monthly_principal_receiva
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    private BigDecimal monthlyPrincipalReceiva;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wing_payment_static_info.early_compensation
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    private BigDecimal earlyCompensation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wing_payment_static_info.cleared_amount
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    private BigDecimal clearedAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wing_payment_static_info.yuqi_repay_amount
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    private BigDecimal yuqiRepayAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wing_payment_static_info.total_monthly_recovery
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    private BigDecimal totalMonthlyRecovery;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wing_payment_static_info.id
     *
     * @return the value of wing_payment_static_info.id
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wing_payment_static_info.id
     *
     * @param id the value for wing_payment_static_info.id
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wing_payment_static_info.people_type
     *
     * @return the value of wing_payment_static_info.people_type
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public String getPeopleType() {
        return peopleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wing_payment_static_info.people_type
     *
     * @param peopleType the value for wing_payment_static_info.people_type
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public void setPeopleType(String peopleType) {
        this.peopleType = peopleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wing_payment_static_info.order_date
     *
     * @return the value of wing_payment_static_info.order_date
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public String getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wing_payment_static_info.order_date
     *
     * @param orderDate the value for wing_payment_static_info.order_date
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public void setOrderDate(String orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wing_payment_static_info.report_month
     *
     * @return the value of wing_payment_static_info.report_month
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public String getReportMonth() {
        return reportMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wing_payment_static_info.report_month
     *
     * @param reportMonth the value for wing_payment_static_info.report_month
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public void setReportMonth(String reportMonth) {
        this.reportMonth = reportMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wing_payment_static_info.order_sum_money
     *
     * @return the value of wing_payment_static_info.order_sum_money
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public BigDecimal getOrderSumMoney() {
        return orderSumMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wing_payment_static_info.order_sum_money
     *
     * @param orderSumMoney the value for wing_payment_static_info.order_sum_money
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public void setOrderSumMoney(BigDecimal orderSumMoney) {
        this.orderSumMoney = orderSumMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wing_payment_static_info.order_sum_count
     *
     * @return the value of wing_payment_static_info.order_sum_count
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public BigDecimal getOrderSumCount() {
        return orderSumCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wing_payment_static_info.order_sum_count
     *
     * @param orderSumCount the value for wing_payment_static_info.order_sum_count
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public void setOrderSumCount(BigDecimal orderSumCount) {
        this.orderSumCount = orderSumCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wing_payment_static_info.has_not_pay_amt
     *
     * @return the value of wing_payment_static_info.has_not_pay_amt
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public BigDecimal getHasNotPayAmt() {
        return hasNotPayAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wing_payment_static_info.has_not_pay_amt
     *
     * @param hasNotPayAmt the value for wing_payment_static_info.has_not_pay_amt
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public void setHasNotPayAmt(BigDecimal hasNotPayAmt) {
        this.hasNotPayAmt = hasNotPayAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wing_payment_static_info.rest_count
     *
     * @return the value of wing_payment_static_info.rest_count
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public Integer getRestCount() {
        return restCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wing_payment_static_info.rest_count
     *
     * @param restCount the value for wing_payment_static_info.rest_count
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public void setRestCount(Integer restCount) {
        this.restCount = restCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wing_payment_static_info.normal_loan_balance
     *
     * @return the value of wing_payment_static_info.normal_loan_balance
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public BigDecimal getNormalLoanBalance() {
        return normalLoanBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wing_payment_static_info.normal_loan_balance
     *
     * @param normalLoanBalance the value for wing_payment_static_info.normal_loan_balance
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public void setNormalLoanBalance(BigDecimal normalLoanBalance) {
        this.normalLoanBalance = normalLoanBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wing_payment_static_info.m1_overdue_loans
     *
     * @return the value of wing_payment_static_info.m1_overdue_loans
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public BigDecimal getM1OverdueLoans() {
        return m1OverdueLoans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wing_payment_static_info.m1_overdue_loans
     *
     * @param m1OverdueLoans the value for wing_payment_static_info.m1_overdue_loans
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public void setM1OverdueLoans(BigDecimal m1OverdueLoans) {
        this.m1OverdueLoans = m1OverdueLoans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wing_payment_static_info.m2_overdue_loans
     *
     * @return the value of wing_payment_static_info.m2_overdue_loans
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public BigDecimal getM2OverdueLoans() {
        return m2OverdueLoans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wing_payment_static_info.m2_overdue_loans
     *
     * @param m2OverdueLoans the value for wing_payment_static_info.m2_overdue_loans
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public void setM2OverdueLoans(BigDecimal m2OverdueLoans) {
        this.m2OverdueLoans = m2OverdueLoans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wing_payment_static_info.m3_overdue_loans
     *
     * @return the value of wing_payment_static_info.m3_overdue_loans
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public BigDecimal getM3OverdueLoans() {
        return m3OverdueLoans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wing_payment_static_info.m3_overdue_loans
     *
     * @param m3OverdueLoans the value for wing_payment_static_info.m3_overdue_loans
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public void setM3OverdueLoans(BigDecimal m3OverdueLoans) {
        this.m3OverdueLoans = m3OverdueLoans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wing_payment_static_info.m4_overdue_loans
     *
     * @return the value of wing_payment_static_info.m4_overdue_loans
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public BigDecimal getM4OverdueLoans() {
        return m4OverdueLoans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wing_payment_static_info.m4_overdue_loans
     *
     * @param m4OverdueLoans the value for wing_payment_static_info.m4_overdue_loans
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public void setM4OverdueLoans(BigDecimal m4OverdueLoans) {
        this.m4OverdueLoans = m4OverdueLoans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wing_payment_static_info.m5_overdue_loans
     *
     * @return the value of wing_payment_static_info.m5_overdue_loans
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public BigDecimal getM5OverdueLoans() {
        return m5OverdueLoans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wing_payment_static_info.m5_overdue_loans
     *
     * @param m5OverdueLoans the value for wing_payment_static_info.m5_overdue_loans
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public void setM5OverdueLoans(BigDecimal m5OverdueLoans) {
        this.m5OverdueLoans = m5OverdueLoans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wing_payment_static_info.m1_overdue_counts
     *
     * @return the value of wing_payment_static_info.m1_overdue_counts
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public Integer getM1OverdueCounts() {
        return m1OverdueCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wing_payment_static_info.m1_overdue_counts
     *
     * @param m1OverdueCounts the value for wing_payment_static_info.m1_overdue_counts
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public void setM1OverdueCounts(Integer m1OverdueCounts) {
        this.m1OverdueCounts = m1OverdueCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wing_payment_static_info.m2_overdue_counts
     *
     * @return the value of wing_payment_static_info.m2_overdue_counts
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public Integer getM2OverdueCounts() {
        return m2OverdueCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wing_payment_static_info.m2_overdue_counts
     *
     * @param m2OverdueCounts the value for wing_payment_static_info.m2_overdue_counts
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public void setM2OverdueCounts(Integer m2OverdueCounts) {
        this.m2OverdueCounts = m2OverdueCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wing_payment_static_info.m3_overdue_counts
     *
     * @return the value of wing_payment_static_info.m3_overdue_counts
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public Integer getM3OverdueCounts() {
        return m3OverdueCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wing_payment_static_info.m3_overdue_counts
     *
     * @param m3OverdueCounts the value for wing_payment_static_info.m3_overdue_counts
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public void setM3OverdueCounts(Integer m3OverdueCounts) {
        this.m3OverdueCounts = m3OverdueCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wing_payment_static_info.m4_overdue_counts
     *
     * @return the value of wing_payment_static_info.m4_overdue_counts
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public Integer getM4OverdueCounts() {
        return m4OverdueCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wing_payment_static_info.m4_overdue_counts
     *
     * @param m4OverdueCounts the value for wing_payment_static_info.m4_overdue_counts
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public void setM4OverdueCounts(Integer m4OverdueCounts) {
        this.m4OverdueCounts = m4OverdueCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wing_payment_static_info.m5_overdue_counts
     *
     * @return the value of wing_payment_static_info.m5_overdue_counts
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public Integer getM5OverdueCounts() {
        return m5OverdueCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wing_payment_static_info.m5_overdue_counts
     *
     * @param m5OverdueCounts the value for wing_payment_static_info.m5_overdue_counts
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public void setM5OverdueCounts(Integer m5OverdueCounts) {
        this.m5OverdueCounts = m5OverdueCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wing_payment_static_info.monthly_principal_receiva
     *
     * @return the value of wing_payment_static_info.monthly_principal_receiva
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public BigDecimal getMonthlyPrincipalReceiva() {
        return monthlyPrincipalReceiva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wing_payment_static_info.monthly_principal_receiva
     *
     * @param monthlyPrincipalReceiva the value for wing_payment_static_info.monthly_principal_receiva
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public void setMonthlyPrincipalReceiva(BigDecimal monthlyPrincipalReceiva) {
        this.monthlyPrincipalReceiva = monthlyPrincipalReceiva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wing_payment_static_info.early_compensation
     *
     * @return the value of wing_payment_static_info.early_compensation
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public BigDecimal getEarlyCompensation() {
        return earlyCompensation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wing_payment_static_info.early_compensation
     *
     * @param earlyCompensation the value for wing_payment_static_info.early_compensation
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public void setEarlyCompensation(BigDecimal earlyCompensation) {
        this.earlyCompensation = earlyCompensation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wing_payment_static_info.cleared_amount
     *
     * @return the value of wing_payment_static_info.cleared_amount
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public BigDecimal getClearedAmount() {
        return clearedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wing_payment_static_info.cleared_amount
     *
     * @param clearedAmount the value for wing_payment_static_info.cleared_amount
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public void setClearedAmount(BigDecimal clearedAmount) {
        this.clearedAmount = clearedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wing_payment_static_info.yuqi_repay_amount
     *
     * @return the value of wing_payment_static_info.yuqi_repay_amount
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public BigDecimal getYuqiRepayAmount() {
        return yuqiRepayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wing_payment_static_info.yuqi_repay_amount
     *
     * @param yuqiRepayAmount the value for wing_payment_static_info.yuqi_repay_amount
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public void setYuqiRepayAmount(BigDecimal yuqiRepayAmount) {
        this.yuqiRepayAmount = yuqiRepayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wing_payment_static_info.total_monthly_recovery
     *
     * @return the value of wing_payment_static_info.total_monthly_recovery
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public BigDecimal getTotalMonthlyRecovery() {
        return totalMonthlyRecovery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wing_payment_static_info.total_monthly_recovery
     *
     * @param totalMonthlyRecovery the value for wing_payment_static_info.total_monthly_recovery
     *
     * @mbg.generated Fri Sep 07 08:59:39 GMT+08:00 2018
     */
    public void setTotalMonthlyRecovery(BigDecimal totalMonthlyRecovery) {
        this.totalMonthlyRecovery = totalMonthlyRecovery;
    }
}