package com.ut.scf.dao.auto;

import com.ut.scf.pojo.auto.WingPaymentYuqiInfo;
import com.ut.scf.pojo.auto.WingPaymentYuqiInfoExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface WingPaymentYuqiInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wing_payment_yuqi_info
     *
     * @mbg.generated Wed Sep 19 16:29:36 GMT+08:00 2018
     */
    long countByExample(WingPaymentYuqiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wing_payment_yuqi_info
     *
     * @mbg.generated Wed Sep 19 16:29:36 GMT+08:00 2018
     */
    int deleteByExample(WingPaymentYuqiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wing_payment_yuqi_info
     *
     * @mbg.generated Wed Sep 19 16:29:36 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wing_payment_yuqi_info
     *
     * @mbg.generated Wed Sep 19 16:29:36 GMT+08:00 2018
     */
    int insert(WingPaymentYuqiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wing_payment_yuqi_info
     *
     * @mbg.generated Wed Sep 19 16:29:36 GMT+08:00 2018
     */
    int insertSelective(WingPaymentYuqiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wing_payment_yuqi_info
     *
     * @mbg.generated Wed Sep 19 16:29:36 GMT+08:00 2018
     */
    List<WingPaymentYuqiInfo> selectByExample(WingPaymentYuqiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wing_payment_yuqi_info
     *
     * @mbg.generated Wed Sep 19 16:29:36 GMT+08:00 2018
     */
    WingPaymentYuqiInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wing_payment_yuqi_info
     *
     * @mbg.generated Wed Sep 19 16:29:36 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") WingPaymentYuqiInfo record, @Param("example") WingPaymentYuqiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wing_payment_yuqi_info
     *
     * @mbg.generated Wed Sep 19 16:29:36 GMT+08:00 2018
     */
    int updateByExample(@Param("record") WingPaymentYuqiInfo record, @Param("example") WingPaymentYuqiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wing_payment_yuqi_info
     *
     * @mbg.generated Wed Sep 19 16:29:36 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(WingPaymentYuqiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wing_payment_yuqi_info
     *
     * @mbg.generated Wed Sep 19 16:29:36 GMT+08:00 2018
     */
    int updateByPrimaryKey(WingPaymentYuqiInfo record);

	List<WingPaymentYuqiInfo> wingPaymentYuqiInfo(WingPaymentYuqiInfo record);

	int getCountByDate(WingPaymentYuqiInfo info);
}