package com.ut.scf.dao.auto;

import com.ut.scf.pojo.auto.FqcrRepayInfo;
import com.ut.scf.pojo.auto.FqcrRepayInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FqcrRepayInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fqcr_repay_info
     *
     * @mbg.generated Mon Aug 13 15:41:55 GMT+08:00 2018
     */
    long countByExample(FqcrRepayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fqcr_repay_info
     *
     * @mbg.generated Mon Aug 13 15:41:55 GMT+08:00 2018
     */
    int deleteByExample(FqcrRepayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fqcr_repay_info
     *
     * @mbg.generated Mon Aug 13 15:41:55 GMT+08:00 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fqcr_repay_info
     *
     * @mbg.generated Mon Aug 13 15:41:55 GMT+08:00 2018
     */
    int insert(FqcrRepayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fqcr_repay_info
     *
     * @mbg.generated Mon Aug 13 15:41:55 GMT+08:00 2018
     */
    int insertSelective(FqcrRepayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fqcr_repay_info
     *
     * @mbg.generated Mon Aug 13 15:41:55 GMT+08:00 2018
     */
    List<FqcrRepayInfo> selectByExample(FqcrRepayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fqcr_repay_info
     *
     * @mbg.generated Mon Aug 13 15:41:55 GMT+08:00 2018
     */
    FqcrRepayInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fqcr_repay_info
     *
     * @mbg.generated Mon Aug 13 15:41:55 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") FqcrRepayInfo record, @Param("example") FqcrRepayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fqcr_repay_info
     *
     * @mbg.generated Mon Aug 13 15:41:55 GMT+08:00 2018
     */
    int updateByExample(@Param("record") FqcrRepayInfo record, @Param("example") FqcrRepayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fqcr_repay_info
     *
     * @mbg.generated Mon Aug 13 15:41:55 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(FqcrRepayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fqcr_repay_info
     *
     * @mbg.generated Mon Aug 13 15:41:55 GMT+08:00 2018
     */
    int updateByPrimaryKey(FqcrRepayInfo record);
}