package com.ut.scf.dao.auto;

import com.ut.scf.pojo.auto.FqcrGuaranyeeHistoryReplayment;
import com.ut.scf.pojo.auto.FqcrGuaranyeeHistoryReplaymentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FqcrGuaranyeeHistoryReplaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fqcr_guaranyee_history_replayment
     *
     * @mbg.generated Mon Jul 16 10:50:42 GMT+08:00 2018
     */
    long countByExample(FqcrGuaranyeeHistoryReplaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fqcr_guaranyee_history_replayment
     *
     * @mbg.generated Mon Jul 16 10:50:42 GMT+08:00 2018
     */
    int deleteByExample(FqcrGuaranyeeHistoryReplaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fqcr_guaranyee_history_replayment
     *
     * @mbg.generated Mon Jul 16 10:50:42 GMT+08:00 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fqcr_guaranyee_history_replayment
     *
     * @mbg.generated Mon Jul 16 10:50:42 GMT+08:00 2018
     */
    int insert(FqcrGuaranyeeHistoryReplayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fqcr_guaranyee_history_replayment
     *
     * @mbg.generated Mon Jul 16 10:50:42 GMT+08:00 2018
     */
    int insertSelective(FqcrGuaranyeeHistoryReplayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fqcr_guaranyee_history_replayment
     *
     * @mbg.generated Mon Jul 16 10:50:42 GMT+08:00 2018
     */
    List<FqcrGuaranyeeHistoryReplayment> selectByExample(FqcrGuaranyeeHistoryReplaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fqcr_guaranyee_history_replayment
     *
     * @mbg.generated Mon Jul 16 10:50:42 GMT+08:00 2018
     */
    FqcrGuaranyeeHistoryReplayment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fqcr_guaranyee_history_replayment
     *
     * @mbg.generated Mon Jul 16 10:50:42 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") FqcrGuaranyeeHistoryReplayment record, @Param("example") FqcrGuaranyeeHistoryReplaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fqcr_guaranyee_history_replayment
     *
     * @mbg.generated Mon Jul 16 10:50:42 GMT+08:00 2018
     */
    int updateByExample(@Param("record") FqcrGuaranyeeHistoryReplayment record, @Param("example") FqcrGuaranyeeHistoryReplaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fqcr_guaranyee_history_replayment
     *
     * @mbg.generated Mon Jul 16 10:50:42 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(FqcrGuaranyeeHistoryReplayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fqcr_guaranyee_history_replayment
     *
     * @mbg.generated Mon Jul 16 10:50:42 GMT+08:00 2018
     */
    int updateByPrimaryKey(FqcrGuaranyeeHistoryReplayment record);
}