package com.ut.scf.dao.auto;

import com.ut.scf.pojo.auto.OrderAssetsInfo;
import com.ut.scf.pojo.auto.OrderAssetsInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderAssetsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_assets_info
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    long countByExample(OrderAssetsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_assets_info
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    int deleteByExample(OrderAssetsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_assets_info
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_assets_info
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    int insert(OrderAssetsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_assets_info
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    int insertSelective(OrderAssetsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_assets_info
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    List<OrderAssetsInfo> selectByExample(OrderAssetsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_assets_info
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    OrderAssetsInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_assets_info
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") OrderAssetsInfo record, @Param("example") OrderAssetsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_assets_info
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    int updateByExample(@Param("record") OrderAssetsInfo record, @Param("example") OrderAssetsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_assets_info
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(OrderAssetsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_assets_info
     *
     * @mbg.generated Sun Sep 02 18:36:37 GMT+08:00 2018
     */
    int updateByPrimaryKey(OrderAssetsInfo record);
}