package com.ut.scf.dao.auto;

import com.ut.scf.pojo.auto.TfProjectAndCorp;
import com.ut.scf.pojo.auto.TfProjectAndCorpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TfProjectAndCorpMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:42 CST 2017
	 */
	long countByExample(TfProjectAndCorpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:42 CST 2017
	 */
	int deleteByExample(TfProjectAndCorpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:42 CST 2017
	 */
	int deleteByPrimaryKey(String projectId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:42 CST 2017
	 */
	int insert(TfProjectAndCorp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:42 CST 2017
	 */
	int insertSelective(TfProjectAndCorp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:42 CST 2017
	 */
	List<TfProjectAndCorp> selectByExample(TfProjectAndCorpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:42 CST 2017
	 */
	TfProjectAndCorp selectByPrimaryKey(String projectId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:42 CST 2017
	 */
	int updateByExampleSelective(@Param("record") TfProjectAndCorp record,
			@Param("example") TfProjectAndCorpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:42 CST 2017
	 */
	int updateByExample(@Param("record") TfProjectAndCorp record, @Param("example") TfProjectAndCorpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:42 CST 2017
	 */
	int updateByPrimaryKeySelective(TfProjectAndCorp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_project_and_corp
	 * @mbg.generated  Fri Oct 27 08:55:42 CST 2017
	 */
	int updateByPrimaryKey(TfProjectAndCorp record);
}