package com.ut.scf.dao.auto;

import com.ut.scf.pojo.auto.TfRateInfo;
import com.ut.scf.pojo.auto.TfRateInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TfRateInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_rate_info
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	long countByExample(TfRateInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_rate_info
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	int deleteByExample(TfRateInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_rate_info
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	int deleteByPrimaryKey(String rateId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_rate_info
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	int insert(TfRateInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_rate_info
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	int insertSelective(TfRateInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_rate_info
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	List<TfRateInfo> selectByExample(TfRateInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_rate_info
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	TfRateInfo selectByPrimaryKey(String rateId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_rate_info
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	int updateByExampleSelective(@Param("record") TfRateInfo record, @Param("example") TfRateInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_rate_info
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	int updateByExample(@Param("record") TfRateInfo record, @Param("example") TfRateInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_rate_info
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	int updateByPrimaryKeySelective(TfRateInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tf_rate_info
	 * @mbg.generated  Fri Oct 27 15:11:19 CST 2017
	 */
	int updateByPrimaryKey(TfRateInfo record);
}