package com.ut.scf.dao.auto;

import com.ut.scf.pojo.auto.RepaymentPlanInfoUn;
import com.ut.scf.pojo.auto.RepaymentPlanUserInfo;
import com.ut.scf.pojo.auto.RepaymentPlanUserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RepaymentPlanUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_info
     *
     * @mbg.generated Fri Aug 03 10:49:12 GMT+08:00 2018
     */
    long countByExample(RepaymentPlanUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_info
     *
     * @mbg.generated Fri Aug 03 10:49:12 GMT+08:00 2018
     */
    int deleteByExample(RepaymentPlanUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_info
     *
     * @mbg.generated Fri Aug 03 10:49:12 GMT+08:00 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_info
     *
     * @mbg.generated Fri Aug 03 10:49:12 GMT+08:00 2018
     */
    int insert(RepaymentPlanUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_info
     *
     * @mbg.generated Fri Aug 03 10:49:12 GMT+08:00 2018
     */
    int insertSelective(RepaymentPlanUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_info
     *
     * @mbg.generated Fri Aug 03 10:49:12 GMT+08:00 2018
     */
    List<RepaymentPlanUserInfo> selectByExample(RepaymentPlanUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_info
     *
     * @mbg.generated Fri Aug 03 10:49:12 GMT+08:00 2018
     */
    RepaymentPlanUserInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_info
     *
     * @mbg.generated Fri Aug 03 10:49:12 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") RepaymentPlanUserInfo record, @Param("example") RepaymentPlanUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_info
     *
     * @mbg.generated Fri Aug 03 10:49:12 GMT+08:00 2018
     */
    int updateByExample(@Param("record") RepaymentPlanUserInfo record, @Param("example") RepaymentPlanUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_info
     *
     * @mbg.generated Fri Aug 03 10:49:12 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(RepaymentPlanUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayment_plan_user_info
     *
     * @mbg.generated Fri Aug 03 10:49:12 GMT+08:00 2018
     */
    int updateByPrimaryKey(RepaymentPlanUserInfo record);
	int insertListRepayment(List<RepaymentPlanUserInfo> repaymentList);
}